umijs/dumi

.gitignore
README.md
lerna.json
package.json
packages/umi-plugin-father-doc/package.json
packages/umi-plugin-father-doc/src/routes/getMenuFromRoutes.ts
packages/umi-plugin-father-doc/src/routes/getRouteConfig.ts
packages/umi-plugin-father-doc/src/routes/getRouteConfigFromDir.ts
packages/umi-plugin-father-doc/src/transformer/index.ts

项目在 windows 下启动开发，有如下问题：
- README.md 中 bash 引导有误
- lerna 中 npmClient 不符
- windows 下缺少 cross-env
- .gitingore 没有 .umi
暂时使用 upath 来统一 '\' 和 '/'，值得再考虑
此条未修复

fix: dev broken on windows

---

packages/umi-plugin-father-doc/src/routes/getRouteConfigFromDir.ts

增加文件主入口，识别文件夹下 `README.md`、 `readme.md` 和 `index.md` 都会被识别成根路径
如 `src/abc/README.md` ， 其路由为 `/abc`

add the default entry src/abc/README.md

---

packages/umi-plugin-father-doc/src/index.ts

title allowed to be empty

---

packages/umi-plugin-father-doc/package.json
packages/umi-plugin-father-doc/src/themes/default/previewer.tsx
packages/umi-plugin-father-doc/src/themes/typings/typings.d.ts

独立 demo 的 desc 是带有 html tags 的字符串，带 tags 传到 codesandbox 会报错，strip 掉了

fix: html tags in desc

---

docs/config/frontmatter.md

docs: fix typo

---

packages/preset-dumi/src/transformer/fixtures/expect/remark-link.html
packages/preset-dumi/src/transformer/fixtures/raw/remark-link.md
packages/preset-dumi/src/transformer/remark/link.ts
packages/preset-dumi/src/transformer/test/remark-link.test.ts

fix(transformer): compatible JSX Link with normal markdown link(#181)

---

packages/create-dumi-app/templates/AppGenerator/package.json.tpl
packages/create-dumi-lib/templates/AppGenerator/package.json.tpl

- windows 系统识别单引号失败，导致 prettier 命令是执行失败
- 修改 package 模板文件中 prettier 命令中的单引号为双引号

fix(scaffold): repair singleton doesn't work in windows

---

packages/preset-dumi/src/themes/default/layout.tsx

各位大佬好，发现dumi在部署github page后有个问题，就是在刷新或第一次进入带锚点的dumi站点链接时，锚点会丢失。这会导致在chrome中无法滚动定位到页面锚点相应位置，具体可看下面几个例子都是这样：
* https://ggeditor.com/guide/getting-started#flow
* https://tsejx.github.io/webpack-guidebook/basic-summary/core-concepts/mode#mode-%E6%A8%A1%E5%BC%8F
* https://annasearl.github.io/anna-remax-ui/components/data-entry/input#input
观察到github page在每次访问时，会自动在url的`location.pathname`最后添加一个斜杠，而在dumi之前的这次提交：https://github.com/umijs/dumi/commit/b16655b4e3c191a886b5681fef44899472465f2f 中，添加了一个自动去除url末尾斜杠的功能。
但是这里在重写url的时候只考虑了`location.pathname`，少加了`location.hash`，所以导致了此问题。经实际部署github page测试，只要加上`location.hash`这问题就解决了。
具体做的修改很简单请看代码，辛苦各位大佬~

fix: 修复部署到github page后刷新页面锚点丢失问题

---

packages/preset-dumi/src/transformer/remark/yaml.ts

-  当新建一个 .md 文件时候， 由于最近更新时间是从 git log 去查询的，所以就导致这个时间是 NaN，从而使得页面渲染的时候 updatedTime 为 1970年 这个错误时间点
#194 
- 获取 updateTime 之后 判断是否为 NaN，若是则抛出错误，就会去获取文件的 mtimeMs

fix(transformer): get NaN updatedTime when create a new md

---

docs/guide/mode.md
packages/preset-dumi/src/plugins/core.ts
packages/preset-dumi/src/themes/default/layout.tsx

- 支持在 `package.json` 中设置 `repository.branch` 来设置 `edit` 的时候跳转的分支，默认为 `master`
- 用 `repository.url` 来代替原先的 `repoUrl`，用 `repository.branch` 设置 `branch`
- 更新 `markdown` 文档
#214

feat(preset): support to set repository branch in package

---

docs/lab/index.md
packages/preset-dumi/src/transformer/fixtures/expect/remark-basic.html
packages/preset-dumi/src/transformer/fixtures/expect/remark-demo.html
packages/preset-dumi/src/transformer/index.ts
packages/preset-dumi/src/transformer/remark/code.ts
packages/preset-dumi/src/transformer/remark/jsxify.ts
packages/preset-dumi/src/transformer/remark/raw.ts
packages/preset-dumi/src/transformer/remark/sourceCode.ts
packages/preset-dumi/src/transformer/utils.ts

- `<pre>` 标签支持高亮源代码，可通过 `lang` 属性配置代码块语言，同时解决重写 transformer 后 `<pre>` 标签内写 JSX 会报错的问题
- 解决 `hast-util-raw` 处理后 Node 的属性值全部变成字符串的问题
- [临时方案] 解决 hast-util-to-jsx 处理后 camelCase 的 props 都被转换成 kebab-case 的问题
- hast-util-raw 和 hast-util-to-jsx 终态还是需要 fork 一份做特殊定制，或者给上游 PR 提升可配置性

fix: jsx output bug in transformer

---

packages/preset-dumi/src/transformer/demo/dependencies.ts
packages/preset-dumi/src/transformer/fixtures/demo-deps/peer/index.ts
packages/preset-dumi/src/transformer/test/demo-deps.test.ts
packages/preset-dumi/src/utils/moduleResolver.ts

比如我在开发组件库 A，peer 了 antd，但 demo 的依赖只识别依赖到 A，那 codesandbox 就只会安装 A，但 A 没有 antd 跑不起来，所以 demo 的依赖应该默认把 A 的 peer 都加进来。
react 的依赖会被重置，其他的peer 依赖会被添加。比如，胡乱改了版本。

feat: support peerDep

---

packages/preset-dumi/src/themes/default/builtins/Previewer.less
packages/preset-dumi/src/themes/default/builtins/Previewer.tsx
packages/preset-dumi/src/themes/default/layout.tsx
packages/preset-dumi/src/transformer/remark/previewer.ts

- 支持 `demo` 锚点
- 修复 `slug` 精准跳转的问题
- `demo` 新增 `id` 属性
- `demo` 的 `title` 支持点击跳转
- 修复 `slug` 精准跳转的问题
- 当跳转到 `demo` 锚点位置时，新增 `target` 样式
#230  
#245

feat(theme): add demo anchor

---

packages/preset-dumi/src/themes/default/layout.tsx

fix: query params get cleared when scroll all the way up to top.

fix: losing query params while scrolling

---

packages/preset-dumi/src/plugins/features/demos.ts
packages/preset-dumi/src/transformer/remark/previewer.ts

- windows 下启动在 `.umi/dumi/demos.ts` 生成的文件格式不对，因为 windows 下的路径片段分隔符是反斜杠，导致解析出问题
- 用 `slash` 处理 `uuid`
#279

fix(transformer): use slash for path to compatible with windows

---

packages/dumi/README.md
packages/theme-default/src/layout.tsx

- 修复切换路由滚动条没有回到顶部
- 修复 `README.md` 中关于 `Development` 的方式未更新的情况

fix(theme): scroller not back to top

---

packages/preset-dumi/src/theme/components/AnchorLink.test.tsx
packages/preset-dumi/src/theme/components/AnchorLink.tsx

- 修复锚点在 Edge 无效的问题
- 锚点滚动用 `window.scrollTo` 来实现，查了一下 兼容性还可以，只不过 `Edge` 貌似不支持 `smooth` 滚动
- [scrollTo的MDN](https://developer.mozilla.org/zh-CN/docs/Web/API/Window/scrollTo)

修复 IE 兼容性问题

---

packages/preset-dumi/src/index.test.ts
packages/preset-dumi/src/plugins/features/demos.ts
packages/preset-dumi/src/theme/hooks/useDemoUrl.test.ts
packages/preset-dumi/src/theme/hooks/useDemoUrl.ts

- 为 runtime 的代码注入 `PLATFORM_TYPE` 用于在运行时判断构建平台
- 修复 basement 构建动态路由的访问路径

fix: demo dynamic route in bmw

---

packages/preset-dumi/src/utils/getHostPkgAlias.ts

在基于 lerna 的项目实践中，当 lerna 所管辖的一个 package 为 private，即私有包时，其中的所有文档将不会自动纳入到 dumi 的路由中，除非通过 .umirc.ts 等类似 [配置](https://d.umijs.org/zh-CN/config#includes) 强制指定 .md 所在的私有包路径（存在后期配置繁琐的问题）。
因为根据 `lerna list --json` 文档，其仅打印 public packages。
存在在私有包中 **应该仍可书写文档** 这样的需求。
> 生成均以 resolve.includes 配置项的值作为基础检测路径，倘若我们不配置该值，则会默认探测 docs 目录、src 目录（普通项目）、packages/pkg/src 目录（lerna 项目）。
在上文对文档引用中，并未提及对于 lerna 项目的处理是否涉及私有包，那么就会出现一种使用现象就是，如论如何自己在私有包中定义的文档都不会被 dumi 纳入到私有路由中，但是又不知道为什么。
1. 并不影响原有功能，且只是对原有 lerna package 探测功能的拓展
1. 尽可能避免用户去额外定义 [config](https://d.umijs.org/zh-CN/config#includes) 来实现私有包中的文档书写

feat: support docs in lerna private packages

---

docs/lab/index.md
docs/lab/index.zh-CN.md
packages/preset-dumi/src/context.ts
packages/preset-dumi/src/fixtures/integrate/.umirc.ts
packages/preset-dumi/src/fixtures/integrate/package.json
packages/preset-dumi/src/fixtures/integrate/src/components/Hello/index.md
packages/preset-dumi/src/fixtures/integrate/src/components/index.md
packages/preset-dumi/src/fixtures/integrate/src/pages/A/index.tsx
packages/preset-dumi/src/fixtures/integrate/src/pages/index.tsx
packages/preset-dumi/src/index.test.ts
packages/preset-dumi/src/index.ts
packages/preset-dumi/src/plugins/features/config.ts
packages/preset-dumi/src/plugins/features/disable.ts
packages/preset-dumi/src/plugins/features/init.ts
packages/preset-dumi/src/plugins/features/menus.ts
packages/preset-dumi/src/plugins/features/navs.ts
packages/preset-dumi/src/plugins/features/routes.ts
packages/preset-dumi/src/routes/decorator/index.ts
packages/preset-dumi/src/routes/decorator/integrate.ts
packages/preset-dumi/src/routes/getRouteConfig.ts
packages/preset-dumi/src/theme/layout.tsx
packages/theme-default/src/components/LocaleSelect.tsx
packages/theme-default/src/test/index.test.tsx

在 Umi 项目安装 `@umijs/preset-dumi` 会进入集成模式，在不破坏原有 Umi 项目的基础上，增加 dumi 的文档路由，适用于管理项目内部不发包的组件的场景。
- 自动探测集成模式：当 `dependencies` 或 `devDependencies` 中包含 `umi` 和 `@umijs/preset-dumi` 时，进入集成模式
- dumi 生成的文档会集中在 `/~docs` 路由下，不干扰原有 Umi 项目的路由（组件 demo 的路由仍然在 `/~demos` 下）
- dumi 文档仅在 `development` 模式下集成，项目进行生产模式构建不会包含 dumi 的任何文档路由
- 自动给 `menus` 和 `navs` 配置中的路由追加 `/~docs` 前缀，意味着同一份配置能同时适用标准模式和集成模式
- 支持通过 `umi build --dumi` or `umi dev --dumi` 参数强制执行只渲染文档部分（即标准 dumi 模式，无路由前缀）
- 所有 dumi 能力在集成模式下均可用
Close #288 #349

feat: umi integrate mode

---

packages/theme-default/src/layout.tsx
packages/theme-default/src/test/index.test.tsx

- 每次 英文都一直显示 上午 下午。。。
|＃  | view|
| - | - |
| Before | ![image](https://user-images.githubusercontent.com/29775873/101487748-8e976c80-3999-11eb-81bc-8ad3660abf0d.png) |
| After |  ![image](https://user-images.githubusercontent.com/29775873/101487799-a0790f80-3999-11eb-87d8-60620d955c9c.png) |
- 优化 footer 时间显示。
- 优化 footer 文字。

perf: optimize footer time show

---

packages/theme-default/src/builtins/SourceCode.less

- 当 code 后直接跟 table 缺失 top
| 🇺🇸 English |   Fix the problem of missing interval between code and table.  |
| 🇨🇳 Chinese |   修复 code 后跟 table 缺失间隔的问题。         |

fix: table miss top under code

---

packages/preset-dumi/src/theme/hooks/useDemoUrl.test.ts
packages/preset-dumi/src/theme/hooks/useDemoUrl.ts

#445 
修复 #445，问题本质是现有 useDemoUrl hook 并未对 hash route 做处理，本 pr 新增 useDemoUrl hook 对 hash route 的处理，且不含 break changes.
| 🇺🇸 English |    support demo url creation in the hash router    |
| 🇨🇳 Chinese |   支持 hash 路由下的 demo url 生成   |

fix(preset): useDemoUrl should work with hash router fix#445

---

packages/preset-dumi/src/utils/getHostPkgAlias.ts

https://github.com/umijs/dumi/issues/470
之前排查以为是路径问题导致，仔细排查发现是windows环境下在执行lerna  ls --json --all 命令时会多出两行日志
```
EnumerateProviders catalog=0
EnumerateProviders totalPro=19
```
从而导致JSON.parse报错
< !--
解决的具体问题。
The specific problem solved.
-->
故采用正则的方式将这两行日志进行替换清除

fix: 修复windows环境lerna项目运行报JSON.parse错误的问题

---

docs/theme/api.md
docs/theme/api.zh-CN.md
jest.config.js
package.json
packages/preset-dumi/package.json
packages/preset-dumi/src/index.test.ts
packages/preset-dumi/src/plugins/features/theme.ts
packages/preset-dumi/src/theme/hooks/usePrefersColor.test.ts
packages/preset-dumi/src/theme/hooks/usePrefersColor.ts
packages/preset-dumi/src/theme/index.ts
packages/preset-dumi/src/theme/layout.tsx
scripts/jest-setup.js

#490 
为了解决暗黑主题的『自动跟随系统』及『手动切换』，新增如下特性：
- 通过 Plugin API 给输出的 HTML 的 `head` 区域添加脚本，用于
1. 初始化 `data-prefers-color` 属性到 HTML 标签上
2. 初始化值的取值顺序：LocalStorage 的存储值 > matchMedia 匹配 'dark' > 默认 'light'
3. 放在 head 内是为了确保 body 的内容被解析时，`data-prefers-color` 的属性选择器就已经生效，避免样式闪动
- 新增 `usePrefersColor` 主题 API，可从 `dumi/theme` 中 import，hook 的返回值为数组
1. 第一个返回值为当前的 `color` **值**，默认值为上一步中 `head` 脚本初始化的 HTML 标签上的值
2. 第二个返回值为反转当前 `color` 的**函数**，执行后 `color` 会进行反转
3. 当反转后的 `color` 值与系统值**不匹配**时，会自动写入 LocalStorage，以便下次载入页面时恢复切换状态
4. 当反转后的 `color` 值与系统值**匹配**时，会清空 LocalStorage 的内容，以便恢复为自动跟随系统的色彩偏好
- dumi 会监听 `prefers-color-scheme` 的 media 规则变化（例如在操作系统的设置中修改了色彩偏好会触发规则变化），并在规则变化的同时更新 HTML 标签上的 `data-prefers-color` 属性值
对于主题开发者：
- 通过 `[data-prefers-color=dark]` 的属性选择器，可以增量编写暗黑模式的主题样式
- 通过 `usePrefersColor` …

feat: usePrefersColor theme API

---

docs/theme/api.md
docs/theme/api.zh-CN.md
packages/preset-dumi/src/plugins/features/theme.ts
packages/preset-dumi/src/theme/hooks/usePrefersColor.test.ts
packages/preset-dumi/src/theme/hooks/usePrefersColor.ts

#490 #543 
此 PR 是 #543 的完善，修改 `usePrefersColor` 主题 API：
- 显式增加 `auto` 的主题色偏好配置，便于开发者向用户开放 `light/dark/auto` 三种配置方式
- hook 返回值从 `[string, () => void]` 变成 `[string, (color: 'light' | 'dark' | 'auto') => void]`，第二参数从切换明亮/黑暗变成设置明亮/黑暗/自动
- 当设置为 `auto` 时主题色偏好将跟随操作系统设置
- 其他逻辑与 #543 中保持一致

feat: split auto mode for usePrefersColor

---

packages/preset-dumi/src/api-parser/fixtures/expect/forwardRef.json
packages/preset-dumi/src/transformer/remark/code.ts
packages/preset-dumi/src/transformer/remark/domWarn.ts
packages/preset-dumi/src/transformer/remark/index.ts
packages/preset-dumi/src/transformer/test/remark-api.test.ts

issues: #524 #418 
PRs: #536 #427 
close #524 
由于 Markdown 语法依赖换行进行段落拆分形成 `p` 标签，但 dumi 扩展的 Markdown 语法会被进一步解析形成新的 DOM 结构，导致部分语法解析后会出现 `p` 嵌套 `h`、`table` 等标签的情况，使得 React 在运行时抛出 `validateDOMNesting(...)` 的警告，不影响功能运行但输出信息会干扰开发者调试组件
解法：
1. 创建通用的 `domWarn` rehype 插件，遍历所有顶层 `p` 下面的扩展 Markdown 语法，并进行位置提升、到父级 `p` 同级
2. 目前会处理的扩展语法包括 `code`、`API`、`embed`
| 🇺🇸 English |  --       |
| 🇨🇳 Chinese |  --       |

fix: react dom warnings from embed, api & code

---

packages/preset-dumi/src/plugins/features/demo/index.ts

在 v1.1.9 中，当 **第一个**  markdown 中和后续 markdown 中各自的 demo 导入同一个文件时，会报 rawCodeX（X 表示数字）未定义的错误。
以 dumi 仓库为示例
1. 在 docs/config/frontmetter.md 和 docs/config/index.md 中任意正文位置加入：
<pre>
```tsx
import React from 'react';
import '../.demos/modal/modal.less';
export default function Button() {
// ...
}
```
</pre>
1. 打开浏览器出现 ReferenceError: rawCode0 is not defined
| 🇺🇸 English |   should avoid override duplicated importation        |
| 🇨🇳 Chinese |        在不同 markdown 中导入同一文件时，不应该覆盖之前的导入   |

fix(preset): avoid overriding duplicated import

---

packages/preset-dumi/src/utils/getRepoUrl.test.ts
packages/preset-dumi/src/utils/getRepoUrl.ts

fix https://github.com/umijs/dumi/issues/562
本来想用正则，后来考虑到有的 url 不填 `http` 或 `https`的。
这里默认不填的还是 https，若用户填写了 http，则 跳转 URL 协议走 http
| 🇨🇳 Chinese | 跳转 URL 链接新增 `http` 协议。         |

feat: repourl support other protocol

---

packages/preset-dumi/src/theme/hooks/usePrefersColor.ts

Safari 上 matchMedia 设置监听器的方法还是 addListener，没有 addEventListener
没有 addEventListener 时使用 addListener。
| 🇺🇸 English | Fix preset compatible with addEventListener of matchMedia.           |
| 🇨🇳 Chinese | 修复预设 matchMedia 的 `addEventListener` 方法兼容性。          |

fix(preset): compatible with addEventListener of matchMedia

---

docs/config/index.md
docs/config/index.zh-CN.md
docs/guide/basic.md
docs/guide/basic.zh-CN.md
packages/preset-dumi/src/context.ts
packages/preset-dumi/src/loader/fixtures/passive.md
packages/preset-dumi/src/loader/index.test.ts
packages/preset-dumi/src/plugins/features/compile.ts
packages/preset-dumi/src/plugins/features/resolve.ts
packages/preset-dumi/src/transformer/remark/codeBlock.ts

resolve #637
#637 
解决的核心需求：不希望渲染所有的 previewLangs，但 pure 不足以满足需求，例如在众多的 tsx 中，我们仅想渲染特定的几个 tsx 为组件，而不是全部，而给每个不想渲染的 tsx 都添加 pure 势必极大增加文档初期工作量
方案：
- 新增 resolve.passivePreview 选项，来支持开启被动渲染，默认为 false，故不存在非兼容性更新
- 在 true 条件下，仅当代码块具有 preview modifier 且属于 previewLangs 时才会被渲染为 demo 组件，否则为常规代码块
效果：
假定有 ```jsx 代码块 A，且 previewLangs 中包含 jsx，那么当
1. resolve.passivePreivew 为 true 时，且A 需要手动添加 preview modifier（即 ```jsx | preview ）时，且 previewLangs 中包含 jsx 时，才会被渲染为组件，而不是常规代码块；
2. resolve.passivePreivew 为 false（默认）时，因 jsx 包含在 previewLangs 中，故走以前的组件代码逻辑，故渲染为代码组件。
| 🇺🇸 English |      add resolve.passivePreview option and preview codeblock modifier     |
| 🇨🇳 Chinese |      新增 resolve.passivePreview 选项，和代码块 preview     |

feat(preset): suppport passive preview

---

packages/theme-default/src/components/LocaleSelect.less
packages/theme-default/src/components/SideMenu.less
packages/theme-default/src/components/SideMenu.tsx

当 navItems 为空的时候，有一些样式错误。
修改后，上面的重复渲染去掉了，下面的修改后如下图

fix: when navItems is void, locale util repeat render

---

packages/preset-dumi/src/plugins/features/demo/index.ts

close #715
背景：现阶段 dumi build 后的 demo 静态文件会存放在 ～/demo/:uuid 目录里，静态文件服务器不专门配置的话找不到对应的demo 文件
解决方案：build 的时候，针对每个 demo 单独生成一个目录
build 后的静态文件支持正确展示 demo

feat: make dynamic route static when dumi build

---

packages/preset-dumi/src/routes/decorator/nav.ts
packages/preset-dumi/src/routes/test/site.test.js

| 🇺🇸 English |  Fix that navigation and menu cannot be generated correctly when using absolute path  |
| 🇨🇳 Chinese |  修复 resolve.includes 使用绝对路径时无法正确生成导航与菜单  |

fix(routes): cannot remove includes prefix when using an absolute path

---

docs/config/index.md
docs/config/index.zh-CN.md
packages/preset-dumi/package.json
packages/preset-dumi/src/context.ts
packages/preset-dumi/src/routes/getRouteConfigFromDir.ts
packages/preset-dumi/src/routes/test/site.test.js

#661 
`resolve` 除了 `includes` 外还希望支持 `excludes`，对 `dumi` 找到的目录进行排除。
| 🇺🇸 English |  `resolve` supports `excludes` configuration to exclude specified directories or files  |
| 🇨🇳 Chinese |  `resolve` 支持 `excludes` 配置排除指定目录或文件  |

feat(routes): resolve supports excludes

---

packages/preset-dumi/src/context.ts
packages/preset-dumi/src/fixtures/demos-htmlsuffix/.umirc.ts
packages/preset-dumi/src/fixtures/demos-htmlsuffix/docs/index.md
packages/preset-dumi/src/fixtures/demos-htmlsuffix/writeTmp.js
packages/preset-dumi/src/index.test.ts
packages/preset-dumi/src/plugins/features/config.ts
packages/preset-dumi/src/plugins/features/demo/index.ts
packages/preset-dumi/src/theme/context.ts
packages/preset-dumi/src/theme/hooks/useDemoUrl.test.tsx
packages/preset-dumi/src/theme/hooks/useDemoUrl.ts

配置 `exportStatic: {}` 或 `exportStatic: { htmlSuffix: true }` 的时候，修复生成以及访问 demo 文件的路径
| 🇺🇸 English |  Demo build correctly when configuring exporStatic    |
| 🇨🇳 Chinese |   demo 正确的构建当配置 exportStatic 时       |

fix: demo build when configuring exportStatic

---

packages/preset-dumi/src/transformer/remark/meta.ts

[856](https://github.com/umijs/dumi/issues/856#issue-983383277)
`meta.filePath`取自`path.relative(process.cwd(), this.data('fileAbsPath')` 而不是 ` path.relative(ctx.umi?.cwd || process.cwd(), this.data('fileAbsPath'))`
| 🇺🇸 English |       when use `APP_ROOT`，fix `Edit this doc on GitHub` link    |
| 🇨🇳 Chinese |    修复当设定`APP_ROOT` 时，`Edit this doc on GitHub`指向问题      |

fix: 当使用APP_ROOT时，在github编辑此页的路径问题

---

packages/preset-dumi/src/plugins/features/resolve.ts

+ #814
`packages/preset-dumi/src/plugins/features/resolve.ts` 处理`resolve`选项时未将`resolve.excludes`赋值给`context`，导致`resolve.excludes`并未生效
| 🇺🇸 English |   Fix the problem that `resolve.excludes` configuration does not take effect        |
| 🇨🇳 Chinese |  修复`resolve.excludes`不生效问题         |

fix(preset): add resolve.excludes to context

---

packages/preset-dumi/src/plugins/features/demo/getDemoRenderArgs.ts

add a InlineRender component to prevent demo being destoryed when layout updates

fix: getDemoRenderArgs

---

packages/preset-dumi/src/fixtures/custom-components/.dumi/theme/builtins/Dir/index.tsx
packages/preset-dumi/src/fixtures/custom-components/.dumi/theme/builtins/Single.tsx
packages/preset-dumi/src/fixtures/custom-components/.umirc.js
packages/preset-dumi/src/fixtures/custom-components/README.md
packages/preset-dumi/src/fixtures/custom-components/plugin.js
packages/preset-dumi/src/index.test.ts
packages/preset-dumi/src/theme/loader.ts

1、开发中无法指定 dumi/theme 的存在文件夹，和现在的构建工具默认 src 目录有点分离，增加了环境变量`process.env.LOCAL_THEME_PATH`
```
"start": "cross-env process.env.LOCAL_THEME_PATH=src dumi dev",
```
2、修复查找theme 组件，只能是文件的问题
之前 
```
builtins
│   ├── Alert.less
│   ├── Alert.tsx
│   └── Button
│       ├── demo
│       │   └── index.tsx
│       ├── index.less
│       ├── index.md
│       └── index.tsx
```
只能找到 Alert 组件，现在可以找到文件夹下存在 index 的组件。

fix: theme find component

---

packages/theme-default/package.json
packages/theme-default/src/builtins/Tree.less
packages/theme-default/src/builtins/Tree.tsx

**When dumi is upgraded to 1.1.32, the error is reported as follows**, The test found that ./Tree.less satisfies the style requirements
```js
This dependency was not found:
* rc-tree/assets/index.less in ./node_modules/dumi-theme-default/es/builtins/Tree.js
To install it, you can run: npm install --save rc-tree/assets/index.less
```
| 🇺🇸 English |      fix module not found problem     |
| 🇨🇳 Chinese |      修复模块未找到问题     |

fix: fix module not found problem

---

packages/theme-mobile/src/layouts/demo.tsx

simulate the touch event error when the DOM is directly mounted on the body or HTML
Close: https://github.com/umijs/dumi/issues/996

fix: simulate the touch event error

---

packages/preset-dumi/src/transformer/demo/dependencies.ts
packages/preset-dumi/src/utils/moduleResolver.test.ts
packages/preset-dumi/src/utils/moduleResolver.ts

https://github.com/umijs/dumi/issues/1105
在lerna场景下codeSandbox的dependencies依赖解析错误，导致在线demo打开都报错
[报错demo链接](https://codesandbox.io/s/swsnsf?file=/App.tsx)
[其他pro-components的在线demo都会报错](https://procomponents.ant.design/components/form)
已在pro-components下npm link测试通过
| 🇺🇸 English |      Fixed the dependency parsing error of codeSandbox in the lerna scenario, resulting in the lack of dependencies in the online demo opening report     |
| 🇨🇳 Chinese |      修复在lerna场景下codeSandbox的dependencies依赖解析错误，导致在线demo打开报缺少依赖问题     |

fix: fix host package dependencies problem

---

src/features/routes.ts

通过umi约定式路由生成的嵌套层级routes
在用户本地编写国际化路由Page时与编写Markdown国际化文件体验不一致
理想写法：✅
实际写法：❌
| 🇺🇸 English |      localize page routes from .dumi/pages     |
| 🇨🇳 Chinese |     本地生成的UmiPage路由通过文件名语言后缀生成国际化路由      |

feat: localize page routes from .dumi/pages

---

src/client/theme-default/slots/Sidebar/index.tsx

- 解决在react17下 Sidebar组件sidebar为空情况下未返回null的bug

fix: nothing was returned from Sidebar render

---

src/features/routes.ts

1.路由id生成规则感觉有点问题，在Monorepo使用下，如果我每个包下面都有一个index.md，就只会出现一个。
2.ID加上包type

fix: monorepo下路由id生成规则不唯一

---

src/features/tabs.ts

- 解决routesTabMapping 没有重复判断问题，导致每次热更新之后一直增加tab

fix: collect-tabs-from-routes

---

docs/guide/page-tab.md
src/features/tabs.ts

1）修改 Tab 文档正则写法
2）暂时去掉 tab id 拼接正则的部分

fix: remove the regular of tab id concatenation

---

src/features/tabs.ts

修复同时使用两个 addContentTab 时,tabs 的 index 不唯一的问题

fix: make sure the tabs index is unique

---

src/client/theme-default/slots/RtlSwitch/index.less

在同时出现多语言、RTL元素时，边距重合，如图：
故在rltSwitch component中添加相关样式。

style: add rtlSwitch margin style

---

src/client/theme-default/slots/PreviewerActions/index.tsx
suites/theme-mobile/src/builtins/Previewer/index.tsx

fix: non-mobile projects do not expand source code display by default

---

src/types.ts
tsconfig.json

https://github.com/umijs/dumi/issues/1387
| 🇺🇸 English |  fix defineConfig parameters typing check in .dumirc.ts file |
| 🇨🇳 Chinese | 修复 .dumirc.ts 文件中 defineConfig 函数传入的参数子项类型校验问题 |

fix: correct defineConfig parameter typing

---

src/features/derivative.ts
src/index.ts

解决当`mfsu`传入`true`时，`dumi`报错无法正常工作的问题
| 🇺🇸 English | mfsu support pass true to use default mfsu config |
| 🇨🇳 Chinese |  mfsu 支持传入 true 以使用默认 mfsu 配置  |

fix: mfsu support pass true to use default mfsu config

---

src/client/theme-api/openCodeSandbox.ts

如果 `tsx` 组件示例没引入 react，codesandbox 预览不会自动导入 react，而 `jsx` 组件示例会导入。原因是 codesandbox 的 [`create-react-app-typescript`](https://github.com/wmonk/create-react-app-typescript) 模板很久就已经不维护了。
而 `create-react-app` 模板已经支持 `tsx` 了，所以可以直接用 `create-react-app` 了。
| 🇺🇸 English | fix codesandbox can't auto import react |
| 🇨🇳 Chinese | 修复 codesandbox 预览不能自动导入 react 的问题 |

fix: codesanbox react not found

---

src/assetParsers/atom.ts
src/features/parser.ts

无
修复 api parser 挪到子线程执行以后的两个问题：
1. 非 `dev/build` 命令执行时挂起的问题，因为在不需要的情况下创建了 parser，导致子线程一直挂起、命令不会终止
2. `assets.json` 生成失败，因为 parser 的子线程被过早销毁，导致后续命令执行中断
| 🇺🇸 English | Fix command & plugin hook bugs that casued by api parser worker thread  |
| 🇨🇳 Chinese | 修复 API 解析器子线程引发的命令执行 bug 和插件 hook 执行 bug |

fix: cmd & plugin hook bugs caused by parser worker thread

---

src/client/theme-api/useSidebarData.ts

无
修复配置式侧边栏在非默认语言的一级路由下不生效的问题，比如 `/en-US/components` 下配置式侧边栏不生效，原因是计算 `/en-US/components` 父级路由的逻辑有问题，将其计算为 `/en-US` 导致获取到错误的侧边栏数据
| 🇺🇸 English | Fix wrong sidebar config for 1-level routes of non-default locales |
| 🇨🇳 Chinese | 修复配置式侧边栏在非默认语言的一级路由下不生效的问题 |

fix: wrong sidebar config for 1-level routes of non-default locales

---

src/client/theme-default/slots/LangSwitch/index.tsx

无
修复非默认语言根路由的语言切换按钮丢失的问题，比如当存在中英文两种语言的时候，`/en-US/components` 是有切换按钮的，但 `/en-US` 的切换按钮丢失了，原因是计算目标切换路由 `/` 的时候返回了空串，所以对空串做了特判
| 🇺🇸 English | Fix lang switch lost in root route of non-default locales |
| 🇨🇳 Chinese | 修复非默认语言根路由的语言切换按钮丢失的问题 |

fix: lang switch lost in root route of non-default locales

---

src/client/theme-api/useSidebarData.ts

#1459
与 #1459 关联的修复，在约定式侧边栏数据生成的过程中，错误地将 `/en-US/a` 归属到 `/en-US` 的侧边栏数据中，但国际化前缀路由不应该参与匹配，导致在访问 `/en-US/a` 路由时，对应的侧边栏数据中缺少自己。
解决方案，在生成父级路由时不处理国际化前缀部分，确保 `/en-US/a` 归属于 `/en-US/a` 下。
| 🇺🇸 English | Fix conventional sidebar missing index route for non-default locales |
| 🇨🇳 Chinese | 修复非默认语言的约定式侧边栏缺少索引路由的问题 |

fix: conventional sidebar missing index route for non-default locales

---

src/client/theme-default/builtins/API/index.tsx
src/client/theme-default/locales/en-US.json
src/client/theme-default/locales/zh-CN.json
src/features/parser.ts

无
优化在未开启 `apiParser` 时使用 API 组件的提示，告诉用户需要先启用配置项；目前提示在解析中，会让用户产生误解。
| 🇺🇸 English | Improve prompt when use API without apiParser enabled |
| 🇨🇳 Chinese | 优化在未开启 `apiParser` 时使用 API 组件的提示 |

refactor: improve prompt when use API without apiParser enabled

---

src/loaders/markdown/index.ts
src/loaders/markdown/transformer/rehypeDemo.ts
src/types.ts

无
背景：
1. demo sources 数据用于将 demo 元数据中源代码的字符串替换为 raw-loader，实现文件复用（比如两个 demo 同时依赖了某一个 util），减小产物尺寸
2. 默认 demo sources 由内置的区块 parser 生成
3. 自定义技术栈目前能修改 demo 元数据中的源代码，但却无法控制 demo sources，这样一旦两者数据对不齐，在 raw-loader 替换的时候就会报错
解法：
1. 自定义技术栈支持修改 demo 引入的源文件列表，这样两份数据都能修改，可以自行保证一致性
2. raw-loader 替换的逻辑考虑异常链路，避免报错
| 🇺🇸 English | Custom tech-stack supports modify demo sources data |
| 🇨🇳 Chinese | 自定义技术栈支持修改 demo 源文件数据 |

feat: custom tech-stack supports modify demo sources data

---

.gitignore
docs/theme/default.md
src/client/theme-api/types.ts
src/client/theme-api/useNavData.ts
src/client/theme-api/utils.ts
src/features/derivative.ts

`themeConfig.nav`支持通过配置模式控制自定义导航的追加模式
| 🇺🇸 English | `themeConfig.nav`support  append mode to change default nav |
| 🇨🇳 Chinese | `themeConfig.nav`支持通过配置模式控制自定义导航的追加模式 |

feat: nav 配置支持追加模式配置导航

---

examples/normal/src/Foo/index.tsx
src/client/theme-default/builtins/API/index.tsx

#1395 
自动 API 组件支持渲染更详细的类型，而不只是简单的 `object`、`function`，效果：
| 🇺🇸 English | API component supports render detailed types |
| 🇨🇳 Chinese | 自动 API 组件支持渲染更详细的类型 |

feat: render detailed types in API component

---

src/features/theme/index.ts

#1490 
Umi 层的逻辑是 `lessLoader.modifyVars` 会覆盖 `theme`，之前 dumi 暗黑模式的选择器变量是通过 `theme` 传入的，这意味着会被用户配置的 `modifyVars` 覆盖，所以改用 chainWebpack 直接改最终的 loader 配置，避免被覆盖
| 🇺🇸 English | Fix built-in dark theme var lost bug if set modifyVars option |
| 🇨🇳 Chinese | 修复配置 modifyVars 时内置暗黑模式选择器变量丢失的 bug |

fix: built-in dark theme var lost if set modifyVars option

---

src/features/compile/index.ts
src/features/tabs.ts
src/loaders/markdown/transformer/index.ts
src/loaders/markdown/transformer/rehypeLink.ts

无
目前 Markdown 中的相对路径链接存在歧义，原因在于 react-router-dom@6 中 `Link` 的行为与 HTML 的 `a` 标签行为[不一致](https://reactrouter.com/en/main/upgrading/v5#note-on-link-to-values)，例如当前页面路径为 `/a`，目标路径为 `./b` 时：
- 在 react-router@6 下最终路径为 `/a/b`，行为类似 `path.resolve(from, to)`
- 在 HTML 规范下最终路径为 `/b`，等同于 `url.resolve(from, to)`
dumi 此前直接将相对路径交给 `Link` 组件跳转，所以都是 react-router@6 的解析逻辑，但 GitHub 预览页显然又是 HTML 的解析逻辑，这使得**同一份 Markdown 的同一个链接在文档站点和 GitHub 预览页之间存在歧义**，肯定是有问题的。
所以这个 PR 做了 3 件事：
1. dumi 是基于 Markdown 生成内容而不是 react-router，所以后续对相对路径的解析会统一使用 HTML 的规范，处理成绝对路径再交给 `Link`
2. 同时对 react-router 的用法做兼容，避免已经在使用 react-router 行为的项目出现问题
3. 最后对 react-router 的用法做警告，建议开发者使用 Markdown 文件的引用方式，因为该方式更简单（特别是像 Ant Design 这类后缀式多语言的站点，还需要考虑 `./xxx-cn` 的情况），不需要考虑 HTML 规范与 react-router@6 行为间的区别，且在 GitHub 预览页也能工作
| …

fix: ambiguous relative link problem in md

---

scripts/sync-from-umi.js
src/client/theme-default/slots/HeroTitle/index.less

无
默认主题的 Hero 标题支持跟随 `@c-primary` 主色改色，效果如下：
Less 转换函数借助该项目生成：https://github.com/nicothin/lessColourFunctionCalculator
| 🇺🇸 English | Hero title follow primary color in default theme |
| 🇨🇳 Chinese | 默认主题的 Hero 标题支持跟随主色变量 |

feat: hero title follow primary color in default theme

---

src/features/derivative.ts

https://github.com/umijs/umi/pull/10527
修复 umi@4.0.53 `routeProps` 特性导致 SSR 构建失败问题
| 🇺🇸 English | Workaround for SSR failed since umi@4.0.53 |
| 🇨🇳 Chinese | 绕过 umi@4.0.53 SSR 构建失败问题 |

fix: workaround for ssr failed since umi@4.0.53

---

src/features/routes.ts
src/features/theme/index.ts
src/utils.ts

Close #1487 
优化主题包内的路由文件（比如 layout 和 dumi 内置的特殊页面），在 `pnpm`/`tnpm` 等项目中构建后生成的 chunk name 过长的问题，某些字符可能会引发静态站点托管服务或 CDN 工作不正常
解法：不解析软连接，使用 `node_modules` 下的原始路径，确保 chunk name 是干净的
| 🇺🇸 English | Make chunk name clean for theme routes |
| 🇨🇳 Chinese | 精简主题包路由文件的 chunk name |

refactor: make chunk name clean for theme routes

---

src/loaders/markdown/transformer/rehypeLink.ts

#1258 
修复 Markdown 中的特殊链接无法工作的问题，比如 `mailto:abc@example.com`、`<a href="xxx" download>xxx</a>`
| 🇺🇸 English | Fix absolute links and schema links lost bug in markdown |
| 🇨🇳 Chinese | 修复 Markdown 中的绝对路径链接及特殊协议链接丢失的问题 |

fix: special links not working bug in markdown

---

examples/normal/.fatherrc.ts
src/features/autoAlias.ts

无
允许修改 autoAlias 特性消费的 father 序列化配置值，用于同时 dumi 和 father 集成封装的场景
| 🇺🇸 English | Allow custom father config for auto alias |
| 🇨🇳 Chinese | 允许修改 autoAlias 特性消费的 father 序列化配置值 |

refactor: allow custom father config for auto alias

---

src/client/theme-api/DumiDemo.tsx
src/client/theme-api/context.ts
src/features/theme/index.ts

配置路由 history 类型为 hash 且用 iframe 形式渲染 demo 时，默认的 demoUrl 没有带上 #，导致渲染结果不正确。
解决方案：参考了1.x的写法，判断是hash路由时给 demoUrl 添加 # 
| 🇺🇸 English | fix: demo url incompatible with hash router  |
| 🇨🇳 Chinese | 修复demoUrl在hash路由下不正确问题 |

fix: demo url incompatible with hash router

---

src/client/theme-default/slots/Header/index.tsx

无
默认主题中引用 `SocialIcon` 组件使用相对路径的方式引入，导致定制主题是如果单独定制 `SocialIcon` 时会出现组件引用错误的情况。
| 🇺🇸 English | To avoid resolving errors in a custom theme, modify the import path of `SocialIcon` in `Header`. |
| 🇨🇳 Chinese | 修改 `SocialIcon` 在 `Header` 中的引用路径，避免自定义主题的情况下解析错误。 |

fix: socialIcons slot cannot override bug

---

src/client/theme-default/builtins/API/index.tsx

暂无
```ts
interface Foo {
bar(): Date; // cause crash!!!
}
```
如上写法，如果 interface 有个字段的定义为 lib 的 `Date` 类型，则会导致解析出来的 `signature` 里面是个 `oneOf` 的 Key （例如下图的 `Date.toString`），而不是正常的 `arguments` 之类的，从而导致渲染 function 类型字符串的时候页面挂了：
目前只发现 `Date` 会有这个问题，也没办法手动复现，看了下 `lib.es5.d.ts` 的 `Date` 的定义也没啥问题。不了解为什么会解析 function 的 signature 为啥会有个 `oneOf`，先从渲染方面修复。
| 🇺🇸 English | Fix <API> crashed in some type definition |
| 🇨🇳 Chinese | 修复某些类型会导致 <API> crash 的问题 |

fix: crash when function type has `oneOf` definition in signature

---

src/service/cli.ts

from https://github.com/umijs/umi/pull/10615
修复 Node.js v14 下 UnhandledPromiseRejectionWarning 只会 warning 不会进程退出的问题
| 🇺🇸 English | Catch unhandled promise rejection for node 14 |
| 🇨🇳 Chinese | 捕获 node 14 下未处理的 Promise rejection |

fix: catch unhandled promise rejection for node 14

---

src/client/theme-api/useNavData.ts
src/client/theme-api/useSiteSearch/searchWorker.ts

Close #1557 
修复由于正则表达式错误引起的相同关键字在不同页面中可能部分匹配丢失的问题
| 🇺🇸 English | Same search keyword may mismatch in different pages |
| 🇨🇳 Chinese | 相同关键字在不同页面中可能部分匹配丢失 |

fix: search keyword may mismatch in different pages

---

scripts/sync-from-umi.js
src/features/derivative.ts

#1570 
允许配置继承自 Umi 的 `monorepoRedirect` 配置项，经测试可以在 dumi 项目中使用
| 🇺🇸 English | Allow monorepoRedirect option from umi |
| 🇨🇳 Chinese | 允许配置继承自 Umi 的 monorepoRedirect 配置项 |

refactor: allow monorepoRedirect from umi

---

src/client/theme-default/slots/ColorSwitch/index.less
src/client/theme-default/slots/RtlSwitch/index.less
src/client/theme-default/slots/SocialIcon/index.less

LangSelect在三个语言及以上时会使用`.dumi-default-lang-select`，而其他组件样式没有把它囊括在内，我本来想把`.dumi-default-lang-select`改成`.dumi-default-lang-multi-switch`但与语义上差太多，所以还是选择现在这个方法

fix: language selector is too close to other components

---

src/assetParsers/atom.ts

无
https://github.com/umijs/dumi/pull/1611 中自定义 watch 参数后，`resolveDir` 仍然用的 `cwd`，可能造成拼接出来的文件路径不存在。
watcher 里的 file 路径相对于 `this.watchArgs.options.cwd`，改用 `this.watchArgs.options.cwd` 可以保证文件路径始终正确。
| 🇺🇸 English |  atom parser uses wacher cwd to resolve full path   |
| 🇨🇳 Chinese |  atom parser 使用 watcher 当前目录拼接文件路径         |

fix: atom parser uses wacher cwd to resolve full path

---

suites/boilerplate/.fatherrc.ts
suites/boilerplate/src/index.ts

Close #1620 
PNPM v8 默认安装依赖声明的最小版本号，如果 create-dumi 模板中的 dumi 版本太旧，如果安装最新的主题包（比如 mobile 或三方主题包）可能会工作异常，做了两个优化：
1. 如果用户安装的是 PNPM v8，则执行 `pnpm up -L` 而非 `pnpm i`
2. create-dumi 构建的时候每次取仓库里当前的 dumi 版本作为模板版本
| 🇺🇸 English | Fix pnpm 8 install minimal version in create-dumi |
| 🇨🇳 Chinese | 修复 create-dumi 使用 pnpm 8 时始终安装最小版本的问题 |

fix: pnpm 8 install minimal version in create-dumi

---

src/types.ts

在defineConfig中使用chainWebpack配置的时候函数参数没有正确的类型推断
| 🇺🇸 English |    Fix the type hinting of chainWebpack       |
| 🇨🇳 Chinese |    修复了配置文件对chainWebpack的类型提示       |

fix: args type of chainWebpck in defineConfig

---

src/loaders/markdown/index.ts

无
修复资产元数据中的 demo 及原子资产 meta 在二次构建后可能部分丢失的问题，原因是 `md-loader` 结果被 webpack 缓存的情况下，与 assets.json 生成有关的钩子就不再执行，而 webpack 持久缓存是默认开启的，最终导致带缓存二次构建时部分元数据丢失。
解决方案：把 md-loader 标记为不可缓存，该行为不会影响性能，因为 dumi 已经对 Markdown 编译启用了自己的持久缓存，md-loader 重复执行也会复用上次编译好的结果。
| 🇺🇸 English | Fix assets metadata may lost due to md loader cache |
| 🇨🇳 Chinese | 修复 loader 缓存导致部分资产元数据丢失的问题 |

fix: assets data may lost due to md loader cache

---

src/loaders/markdown/index.ts

This reverts commit 7b0a3fdde7615e493f3cce95234221398a351cb8.
Since #1649 
禁用 loader 缓存后在 antd 项目中发现热更新耗时会非常长，固先 revert 之前的修复方案，后续再找其他办法解决
| 🇺🇸 English | Fix HMR spent a long time due to disable loader cache |
| 🇨🇳 Chinese | 修复 HMR 在禁用 loader 缓存后耗时过长的问题 |

fix: hmr spent a long time due to disable loader cache

---

docs/theme/default.md
src/client/theme-api/types.ts
src/client/theme-default/builtins/SourceCode/index.less
src/client/theme-default/builtins/SourceCode/index.tsx
src/client/theme-default/slots/Toc/index.tsx

[1639](https://github.com/umijs/dumi/issues/1639)
基于 `themeConfig.showLineNum`值判断是否添加代码行号。
| 🇺🇸 English |     feat: add line mum for source code content      |
| 🇨🇳 Chinese |     feat: 代码块增加行号展示      |

feat: support to show line number for SourceCode (#1639)

---

docs/config/markdown.md
docs/guide/conventional-routing.md
docs/theme/api.md
src/client/theme-api/context.ts
src/client/theme-api/types.ts
src/client/theme-api/useNavData.ts
src/client/theme-api/useSidebarData.ts
src/client/theme-api/utils.ts
src/client/theme-default/slots/Navbar/index.less
src/constants.ts
src/features/theme/index.ts
suites/theme-mobile/package.json

Related #1665 
RFC #1618 
解决约定式二级导航在主题包及存量项目中的向前兼容问题。
由于约定式二级导航会修改主题 API hook 的返回结果，为了保证向前兼容，依据 dumi 版本号的声明来决定是否默认启用二级导航，同时升级脚手架及移动端主题包中的 dumi 声明版本号，详见上述 RFC 链接中的向前兼容部分。
另外该 PR 还包含对 #1665 的两个优化点，由于二级导航特性尚未发布就合并在该 PR 里了：
1. `nav.parent` 的用法改成 `nav.second`，语义上更清晰，顺便解决了一级、二级导航的 meta 展示串台的问题
2. 优化导航下拉菜单的样式

refactor: improve 2-level nav forward compatibility

---

src/client/theme-api/DumiDemo.tsx
src/loaders/markdown/transformer/rehypeDemo.ts
src/techStacks/react.ts

Related: https://github.com/ant-design/ant-design/pull/42255
为 demo 包裹 `React.memo` 避免不必要的重新渲染，demo 没有 props 不需要响应父级的 re-render

perf: avoid unnecessary re-rendering for demos

---

src/loaders/markdown/transformer/index.ts

| 🇺🇸 English |    fix: useless arg lead to ts type error       |
| 🇨🇳 Chinese |     修复 unified 插件传参与定义不一致导致的ts error      |

chore: remove useless plugin opts in md transformer

---

src/client/theme-default/slots/SearchBar/Input.tsx

https://github.com/umijs/dumi/issues/1640 之前也有issue反馈类似问题
这个链接可以复现问题 [https://github.com/tgxpuisb/dumi-demo](https://github.com/tgxpuisb/dumi-demo)
Versions
- dumi: ^2.2.1
- node: >=14.18.1
- npm: 6.14.15
- OS: MacOS
- Browser: chrome 112.0.5615.138（正式版本） （64 位）
- react: 16.14.0
- react-dom: 16.14.0
在react16版本下，在搜索输入框中输入内容时报空指针错误。
查询原因与解决方案如下：
[https://github.com/tgxpuisb/dumi-demo/blob/master/README.md](https://github.com/tgxpuisb/dumi-demo/blob/master/README.md)
该问题在React高版本中没有复现，但考虑到React16版本还在大量使用中，还是期望能修复一下
不需要

fix: search box may throw error in react 16

---

src/client/theme-default/slots/Toc/index.tsx

Close #1771 
修复非根目录部署时点击相同锚点会错误跳转到首页的问题
| 🇺🇸 English | Fix same anchor jump incorrectly when set base |
| 🇨🇳 Chinese | 修复非根目录部署时点击相同锚点会跳转错误的问题 |

fix: same anchor jump incorrectly when set base

---

src/client/typings.d.ts
src/features/configPlugins/schema.ts

Close #1740 
修复配置 `resolve.atomDirs.[n].subType` 时 schema 校验不通过的问题
| 🇺🇸 English | Fix schema definition for subType of atomDirs config |
| 🇨🇳 Chinese | 修复 atomDirs 配置项中 subType 的 schema 定义 |

fix: schema definition for subType of atomDirs config

---

src/client/theme-api/DumiPage.tsx
src/features/theme/index.ts

Close #1750 
修复启用 nprogress 时，打开自定义 React 页面进度条不会完成的 bug，原因是之前仅对 Markdown 异步路由的加载状态做了捕获
新的解决方案是借助 Suspense 的 fallback 组件（也就是 Umi 的 loading 组件）来设置加载状态，dumi 总是会内置一个空白 loading 来处理加载逻辑，如果用户有配置 loading 时，dumi 的内置 loading 则会包在用户的外面，不影响原有功能
这个方案相比原方案的好处是：
1. 不局限于 Markdown 路由，而是针对所有异步路由生效（修复原始 issue）
2. fallback 组件 mount 时开始加载，unmount 时完成加载，时机上比监听 history 更简洁
3. 再次访问已经完成异步加载的页面时不会再展示 loading
| 🇺🇸 English | Fix nprogress always pending in custom react pages |
| 🇨🇳 Chinese | 修复自定义 React 页面中的 nprogress 始终处于加载态的问题 |

fix: nprogress always pending in custom react pages

---

src/features/compile/index.ts
src/loaders/markdown/transformer/index.test.ts
src/loaders/markdown/transformer/index.ts
src/loaders/markdown/transformer/rehypeDemo.ts
src/loaders/markdown/transformer/remarkMeta.ts
src/types.ts
src/utils.ts

Close #1780 
修复代码块 demo 在相同路由的不同 locale 或 tab 中会冲突的问题，例如 `docs/test`、`en-US/docs/test`、`docs/test?tab=other` 这 3 个路由下的代码块 demo 会冲突，原因是生成的 demo id 重复了
解决方案：给代码块 demo 的 id 中加上 locale 和 tab 的后缀，例如 `docs-test-demo-0-en-us` 或 `docs-test-demo-0-other`
除此之外顺便修复了自动 `atomId` 在带 locale 或 $tab 后缀的原子资产 Markdown 文件中生成失败的问题，这会导致 `src/Foo/index.md` 以 `foo-` 作为 demo id 前缀，而 `src/Foo/index.en-US.md` 却以 `src-foo-` 作为 demo id 前缀，天然区分开来了，这可能也是此前该问题没有用户反馈的原因之一
| 🇺🇸 English | Fix code block demos conflict bug in different locale route |
| 🇨🇳 Chinese | 修复代码块 demo 在不同 locale 路由中会冲突的问题 |

fix: code block demos conflict in different locale

---

.dumi/theme/slots/HeaderExtra/index.less
.dumi/theme/slots/HeaderExtra/index.tsx
src/client/theme-default/layouts/DocLayout/index.tsx
src/client/theme-default/slots/Content/index.less
src/client/theme-default/slots/Content/index.tsx
src/client/theme-default/slots/RtlSwitch/index.less

Close #1789 
包含和 Content 有关的几处样式改进：
1. 页面内容区域增加 min-height，避免在内容过少时 Footer 部分往上顶
2. 通过 FrontMatter 手动禁用 sidebar 时不再展示 Content 容器，和首页的状态一致
3. 优化 `hr` 在暗色模式下的样式
另外顺便修改了 RTL 开关在暗色模式下的边框颜色
| 🇺🇸 English | Improve min-height and no-sidebar mode for content area |
| 🇨🇳 Chinese | 改进内容区域的 min-height 及关闭 sidebar 情况下的样式 |

refactor: improve min-height and no-sidebar mode for content

---

docs/guide/faq.md
docs/theme/default.md
src/client/theme-default/slots/ContentFooter/index.less
src/loaders/markdown/transformer/rehypeDemo.ts

#1796 
修复内容区域底部上一篇/下一篇链接在 Chrome 下的样式问题，原因是用了 `float` 的 `inline-start/inline-end` 值便于实现 RTL 模式，但该规范目前只有 Firefox 和 Safari 支持，参考：https://developer.mozilla.org/zh-CN/docs/Web/CSS/float#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7
另外顺便改了 2.2.2 的另外两个问题，不希望用户感知，不新提 PR 了：
1. 完善 `lastUpdated` 的配置项文档说明，并补充在 GitHub Action 中部署的注意点
2. 把 #1796 中对 tab 页 demo id 生成时的冗余调整去掉，避免 demo id 中包含两遍 tab key
| 🇺🇸 English | Fix style compatibility bug for content footer navigation |
| 🇨🇳 Chinese | 修复内容区域底部导航的样式兼容性问题 |

fix: style compatibility for content footer navigation

---

.github/workflows/ci.yml
packages/preset-dumi/package.json
packages/preset-dumi/src/index.test.ts
packages/preset-dumi/src/plugins/features/compile.ts
packages/preset-dumi/src/transformer/demo/index.ts
packages/preset-dumi/src/transformer/fixtures/expect/demo-await-import.js

https://github.com/ant-design/ant-design-pro/issues/10829
dumi v1 没有锁定 babel 版本但 Umi 3 预打包变相锁定了 babel 及相关插件的版本，而 `@babel/core@^7.22.6` 和 Umi 3 预打包的插件不兼容，会导致 demo 编译报错
解决方案：考虑到 Umi 3 升级 babel 的改动影响不好评估，所以锁定 dumi v1 版本的 babel 依赖与 Umi 3 预打包的 babel 保持一致，以修复该问题
| 🇺🇸 English | Fix babel compile failed for demo |
| 🇨🇳 Chinese | 修复 babel 编译 demo 失败的问题 |

fix: babel compile failed for demo

---

packages/preset-dumi/src/transformer/demo/options.ts

#1817 
https://github.com/ant-design/ant-design-pro/issues/10829
修复 dumi v1 在 package.json 包含 `browserslist` 配置时，demo 编译可能报错的问题。
该 PR 是 #1817 的补充，锁定 babel 版本只能解一小部分问题，在 ant-design-pro 项目中报错的真正原因是 package.json 配置中的 `browserslist` 配置值为百分比，但 browserslist 版本和 babel 版本对不上导致 targets 校验报错，解法是为 demo 编译的 babel 配置启用 `ignoreBrowserslistConfig` 配置项。
补充：
dumi demo 编译也是使用的 Umi 的 babel 配置，为什么 Umi 的 babel 编译不会报错而 dumi 的 demo 编译会报错？因为 babel 仅在未配置 `targets` 时才会尝试读取 `browserslist` 配置，Umi 层默认有 `targets` 所以不受影响，而 dumi demo 编译为了提升编译效率，没有配置 `targets` 所以走了自动读取 `browserslist` 的逻辑。
| 🇺🇸 English | Ignore browserslist config when compiling demo |
| 🇨🇳 Chinese | 编译 demo 时忽略 browserslist 配置 |

fix: ignore browserslist config when compiling demo in v1

---

src/client/theme-default/slots/SearchBar/index.tsx

https://github.com/umijs/dumi/blob/master/src/client/theme-default/slots/SearchBar/index.tsx#L6C44-L6C44
在 `SearchBar` 中 引入 `SearchResult` 的方式有问题， 导致无法通过主题自定义 `SearchResult` 组件
| 🇺🇸 English |      fix: support to custom SearchResult     |
| 🇨🇳 Chinese |     修复：支持自定义SearchResult组件      |

fix: cannot customize SearchResult slot

---

src/client/theme-api/useTabMeta.ts

无
修复在 MemoryHistory 场景下，页面 Tab 切换后 query 更新不正确的问题，这会导致 `useLocation` 拿到的 `search` 值不正确，影响包含 TOC 链接地址在内的其他功能。
原因是 MemoryHistory 的 push 方法不会自动对 `params` 参数加上 `?` 前缀，与 BrowserHistory 的行为不一致，复现链接：https://codesandbox.io/s/quirky-fast-xgvcyy?file=/src/App.js
解法是手动补上 `?` 前缀确保无论在 MemoryHistory 还是 BrowserHistory 下都可以工作。
| 🇺🇸 English | Fix incorrect tab query in memory history |
| 🇨🇳 Chinese | 修复 memory history 下 tab query 参数不正确的问题 |

fix: incorrect tab query in memory history

---

src/features/theme/index.ts

Close #1816 
修复页面整体重新加载（例如刷新浏览器标签页）时，toc 不展示的问题，原因是 #1793 改了 loading 状态更新的逻辑，非前端路由切换不再更新 loading 状态，所以默认的 loading 状态需要从 `true` 调整为 `false`。
| 🇺🇸 English | Fix toc lost bug when page is full reload |
| 🇨🇳 Chinese | 修复页面整体重新加载时 TOC 丢失的问题 |

fix: toc lost bug when page is full reload

---

src/client/theme-default/builtins/SourceCode/index.tsx

Taking [Ant Design's docs](https://ant.design/docs/react/use-with-create-react-app#import-antd) as an example:
```bash
$ npm install antd --save
```
When you click the "Copy" button, the result will be:
`$ npm install antd --save`
After applying the code from this commit, the result will be:
`npm install antd --save`
This is more in line with expectations.
| 🇺🇸 English | remove leading spaces and specific characters when copying shell code in `SourceCode` |
| 🇨🇳 Chinese | 在 `SourceCode` 中复制 shell 代码时，去除行首的空格和特定字符 |

feat: omit prefix symbol automatically when copying shell code

---

src/features/routes.ts

无
修复默认配置情况下，在原子资产目录（`src`）下的 Markdown 文件变化时路由表不会更新的问题，原因是生成 watch 目录的逻辑不对，应该在钩子函数里取 `api.config` 基于最终配置生成 watch 目录。
| 🇺🇸 English | Fix routes not updated when atom md file is changed |
| 🇨🇳 Chinese | 修复原子资产 md 文件变更时路由表不更新的问题 |

fix: routes not updated when atom md file is changed

---

src/client/theme-default/layouts/DocLayout/index.tsx

fix #1844 
| 🇺🇸 English |     Fix custom ContentFooter slots not working      |
| 🇨🇳 Chinese |     修复 ContentFooter 无法自定义问题      |

fix: cannot customize ContentFooter slot

---

docs/guide/faq.md

咨询问题
文档部署，GITHUB_TOKEN 失效问题和流程
更新部署部分文档
| 🇺🇸 English |      Update deploy document     |
| 🇨🇳 Chinese |     更新部署文档      |

docs: improve deployment guide in faq

---

src/client/theme-api/useNavData.ts
src/client/theme-api/useSidebarData.ts

- #1815 
在英文下，`src` 目录的路由名称被解析成了分组的名称
| 🇺🇸 English |     the resolution of the src directory does not work in english      |
| 🇨🇳 Chinese |     英文下 src 目录解析失效      |

fix: incorrect conventional 2-level nav in localized routes

---

src/client/theme-default/slots/Toc/index.tsx

Close #1842
修复二次访问加载过的页面时，TOC 可能会丢失的问题；原因是 useEffect 没有响应 `memoToc` 数据的变更
| 🇺🇸 English | Fix toc may lost when visiting loaded pages |
| 🇨🇳 Chinese | 修复二次访问加载过的页面时 TOC 可能会丢失的问题 |

fix: toc may lost when visiting loaded pages

---

examples/normal/.dumi/pages/loader-test.tsx
src/features/compile/index.ts
src/loaders/markdown/index.ts

暂时保留了 meta，meta 改造完可以删掉
| 🇺🇸 English |    mdLoader support `demo` `demo-index` `frontmatter` `text` as query       |
| 🇨🇳 Chinese |  mdLoader 支持 `demo` `demo-index` `frontmatter` `text` 作为 query 参数        |

feat: split markdown meta loader

---

src/client/theme-api/useRouteMeta.ts
src/templates/meta-frontmatter.ts.tpl
src/templates/meta-route.ts.tpl
src/templates/meta-runtime.ts.tpl

refactor: better frontmatter code

---

src/features/locales.ts
suites/theme-mobile/src/builtins/Previewer/index.tsx

| 🇺🇸 English |     Fix demos without language configuration      |
| 🇨🇳 Chinese |    修复 demos 没有语言配置       |

fix: locale cannot apply for independent demo routes

---

src/loaders/markdown/transformer/fixtures/react-component/expect.ts
src/loaders/markdown/transformer/fixtures/react-component/index.md
src/loaders/markdown/transformer/rehypeRaw.ts

Close #1836 
Ref: #1861 
修复 Markdown 组件属性上的标签被意外转换的 bug，解法有两个：
1. 参考 #1861 对正则做优化，仅 `<Foo ` 或 `<Foo>` 的匹配才被认定为是组件，这样可以直接过滤掉类似 `Array<Function>` 的类型声明
2. 在正则匹配替换时，对匹配字符串的前后内容做识别，如果发现是 `="...{匹配值}..."` 就认定是在属性内的值不做处理，这样可以覆盖类似 `<CodeEditor value="<Foo bar></Foo>"></CodeEditor>` 的场景
| 🇺🇸 English | Fix unexpected transform for tags within attribute |
| 🇨🇳 Chinese | 修复属性内的标签字符串被意外转换的问题 |

fix: unexpected transform for tags within attribute

---

scripts/sync-from-umi.js

```
$ PORT=3000 dumi dev
$ set PORT=3000&&umi dev
```
fix 
```
$ set PORT=3000&&umi dev
```
to
```
$ set PORT=3000&&dumi dev
```
| 🇺🇸 English |     set PORT=3000&&dumi dev      |
| 🇨🇳 Chinese |      set PORT=3000&&dumi dev     |

docs: correct env config content from upstream

---

src/features/derivative.ts
suites/boilerplate/templates/react/tsconfig.json.tpl
suites/boilerplate/templates/site/tsconfig.json.tpl
tsconfig.json

无
之前 tsconfig.json `include` 配置项的脚手架默认值和框架警告提示都包含 `.dumi/**/*`，示例：
```bash
warn  - Please append `.dumi/**/*` & `.dumirc.ts` into `include` option of `tsconfig.json`, to make sure the types exported by framework works.
```
如果用户照做的话，会导致 dumi 的临时文件目录 `.dumi/tmp` 也被包含进去，在项目执行 tsc 时将会包含不必要的检查，甚至可能抛出不该用户关心的类型错误。
所以该 PR 做了 3 处改动：
1. 对脚手架的 tsconfig.json 均去除 `.dumi/**/*`
2. 对存量 tsconfig.json 检测到 `.dumi/**/*`（用户已修复过）会自动帮用户去除，并根据需要把 `.dumi` 下的其他文件加进去，尽可能让已经处理过的用户或通过新脚手架创建的用户不感知这个二次修复
3. 对存量 tsconfig.json 未检测到 `.dumi/**/*`（用户还没修复过），但同时又使用到 `.dumi` 文件夹下的 TypeScript 约定式文件（比如 `.dumi/app.tsx`、`.dumi/theme/**/*`）做针对性警告提示，建议用户将它们添加到 tsconfig.json include 中
额外说明：为什么需要额外将 `.dumi` 下的 TypeScript 文件添加到 `include` 中？因为 `include` 的默认值是 `**/*`，不包含 `.` 开头的隐藏文件，如果不添加的话会导致相关文件丢失 TypeScript 类型提示
| Language   | …

fix: tsconfig include default value and warning msg

---

src/features/derivative.ts

#1902 
优化对 `.dumi` 目录的自动 tsconfig.json 更改逻辑的实现，从往根目录 tsconfig.json 添加 `include` 值改为在子目录创建 tsconfig.json，后者是对原项目侵扰更少，且复杂度更低的方案，同样可以为 `.dumi` 目录下的文件启用类型识别
| 🇺🇸 English | Improve the auto tsconfig logic for dot dumi dir |
| 🇨🇳 Chinese | 改进为 .dumi 生成自动 tsconfig 的逻辑 |

refactor: improve the auto tsconfig logic for dot dumi dir

---

src/loaders/markdown/transformer/index.ts
src/loaders/markdown/transformer/remarkMeta.ts

| 🇺🇸 English |     add absolute addresses for plugin development      |
| 🇨🇳 Chinese |      为插件开发者提供 绝对地址      |

refactor: share markdown absolute path with custom unified plugins

---

docs/guide/markdown.md
src/loaders/markdown/transformer/index.ts

Maybe resolve #1729
| 🇺🇸 English |     improved plugin loading      |
| 🇨🇳 Chinese |    改进 extraRemarkPlugin 加载方式       |

fix: cannot apply pure esm unified plugin

---

src/client/theme-api/useRouteMeta.ts
src/client/theme-api/useSiteSearch/index.ts
src/client/theme-api/useSiteSearch/useSearchData.ts
src/client/theme-default/slots/SearchBar/Input.tsx
src/client/theme-default/slots/SearchBar/index.tsx
src/features/compile/index.ts
src/features/meta.ts
src/loaders/markdown/index.ts
src/loaders/markdown/transformer/rehypeDemo.ts
src/templates/meta-demos.ts.tpl
src/templates/meta-route.ts.tpl
src/templates/meta-search.ts.tpl
src/utils.ts

- feat: use new loader for search
- feat: search support tsx
- feat: split meta chunk
- feat: load meta on hover

feat: merge chunk & optimize meta loading

---

src/client/theme-api/useSiteSearch/index.ts
src/client/theme-default/slots/SearchBar/index.tsx
src/client/theme-default/slots/SearchResult/index.tsx

1. 搜索框聚焦时同样会加载异步 chunk（通过键盘搜索）
2. 只在初次输入时显示 loading
| 🇺🇸 English |      -     |
| 🇨🇳 Chinese |      -     |

perf: loadSearchData on focus & show loading only once

---

src/loaders/markdown/index.ts
src/utils.ts

无
Markdown loader 编译的缓存 key 从 mtime 变为 contenthash，这样可以实现在 CI/CD 平台中复用缓存，因为这类平台拉取代码时通常不会保留 git history，mtime 是不可靠的
| 🇺🇸 English | Use content hash as cache key for markdown loader |
| 🇨🇳 Chinese | Markdown loader 改用 content hash 作为缓存键 |

refactor: use content hash as cache key for md loader

---

packages/preset-dumi/src/transformer/demo/index.ts
packages/preset-dumi/src/transformer/fixtures/expect/demo-await-import.js

Close #1920
修复 dumi v1 demo 预编译结果中包含非预期 `exports` 导致编译报错的问题。
大致原因：
- 虽然 dumi 锁了 babel，但非预打包的方式锁不了间接依赖，由 @babel/plugin-transform-modules-commonjs 间接引用到了更新的 babel 版本，和 @umijs/babel-preset-umi 用到的预打包的 babel 版本对不上
- 使用 [Babel REPL](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAE2AMwIYFcA28AUBKOAXgD44BvAXyA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.23.1&externalPlugins=&assumptions=%7B%7D) 测试最新版本是正常的（不会出现类似 `exports['default'] = function _default() {}` 的语句）
- 所以推测该问题是因为间接使用不同版本的 babel …

fix: unexpected exports in demo pre-compiling result

---

src/client/theme-api/useNavData.ts
src/client/theme-api/useSidebarData.ts

无
修复在非默认语言下，约定式二级导航菜单可能丢失的问题，也会出现默认语言和非默认语言下导航二级菜单不一致的情况
后续：约定式路由相关逻辑的复杂度较高，需要补充用例确保迭代过程中的功能稳定
| 🇺🇸 English | Fix conventional 2-level nav lost in localized routes |
| 🇨🇳 Chinese | 修复非默认语言下二级导航丢失的问题 |

fix: conventional 2-level nav lost in localized routes

---

src/client/theme-default/layouts/DocLayout/index.tsx
src/client/theme-default/slots/SearchResult/index.tsx

…ng position
**背景**：
搜索内容时(h1)，hash被清空后，没有滚动到对应的区域
**解决方案**：
当hash被清空后，滚动到h1对应位置，对应顶部
| 🇺🇸 English |      fixed the hash was cleared and did not scroll to the corresponding position.     |
| 🇨🇳 Chinese |      修复hash被清空，没有滚动到对应位置     |

fix: wrong search scroll position of 1-level heading in current page

---

src/features/parser.ts

#1981 
修复过滤 API 元数据时未处理异常 `oneOf` 和 `allOf` 导致报错的问题
| 🇺🇸 English | Handle unexpected oneOf and allOf for api metadata |
| 🇨🇳 Chinese | 处理 API 元数据中异常的 oneOf 和 allOf 值 |

fix: handle unexpected oneof and allof for api metadata

---

src/constants.ts
src/features/compile/index.ts
src/utils.ts

无
支持通过 `cacheDirectoryPath` 配置项控制 dumi 编译的持久缓存位置
| 🇺🇸 English | Control compile fs cache location by `cacheDirectoryDir` config |
| 🇨🇳 Chinese | 支持通过 `cacheDirectoryDir` 控制编译持久缓存位置 |

refactor: cache dir config can control compile fs cache location

---

src/features/theme/index.ts

| 🇺🇸 English |     parseModuleSync to parseModule Fix for some scenarios where uninitialized results returned a promise      |
| 🇨🇳 Chinese |     parseModuleSync 改为 parseModule 修复 某些场景下未初始化导致结果返回 promise 的问题      |

refactor: use async way to parse theme modules

---

docs/guide/faq.md

网站、文档、Demo 改进 / Website, documentation, demo improvements
No related issue
When I use dumi, i found the config file is ineffective, finally, it's related with the APP_ROOT env.
更新指南-常见问题-如何在 cra 等非 umi 项目中使用 dumi 中关于.dumirc.js的使用。

docs: improve cra usage in faq

---

src/client/pages/Demo/index.ts
src/client/theme-api/useLiveDemo.ts
src/client/theme-default/builtins/Previewer/index.less
src/client/theme-default/builtins/Previewer/index.tsx
src/client/theme-default/slots/PreviewerActions/index.tsx
src/features/configPlugins/schema.ts
src/features/derivative.ts
src/loaders/markdown/index.ts
src/loaders/markdown/transformer/index.ts
src/types.ts

#1992 
修复 #1992 引入的几处 bug，分别是：
1. 由于 demo parser 与编译 resolver 的 `mainFields` 不一致引起的多实例问题（同时引入某个依赖的 cjs 和 esm 产物）
2. live demo 错误状态在 compact demo 中溢出容器的问题， from @jeffwcx 
3. resolveMap 包含依赖解析路径导致运行时的 demo 依赖元数据出现错乱的问题，from @jeffwcx 
另外做了两个改进：
1. 恢复 `live` 配置项并添加警告，避免 Ant Design 的 CI 报错，等正式版再移除
2. `useLiveDemo` 的 API 调整，`setSources` 变成 `setSource`，设置 demo 的源码，把源码文件当做一个整体更合适

fix: multi-instance problem and styles of live demo feature

---

src/features/theme/index.ts
src/loaders/markdown/transformer/index.ts
src/templates/meta/exports.ts.tpl

#1974 
在 #1974 中 `useRouteMeta` 的返回值无意中从 `{ tabs?: IRouteTabMeta[], ... }` 变成了 `{ tabs: IRouteTabMeta[], ... }`，没有 tab 的时候也有空数组，这本质上是 Breaking Change，会导致基于 `tabs` 字段是否存在来做差异化逻辑的项目运行异常（比如 Ant Design 官网），所以将返回值重新调回去
另外顺便改了两个 warning 版本的警告判断逻辑，避免 2.3.0 非正式版的应用也收到错误

refactor: avoid breaking change for useRouteMeta api

---

docs/guide/faq.md

修改使用github action部署dumi文档，现在github 默认是main分支，所以将文档中的master改成了main

docs: ci branch from master to main

---

src/client/misc/reactDemoCompiler.ts
src/client/theme-api/types.ts
src/client/theme-api/useLiveDemo.ts
src/client/theme-api/useSiteSearch/useSearchData.ts
src/client/theme-default/builtins/Previewer/index.less
src/client/theme-default/builtins/Previewer/index.tsx
src/client/theme-default/slots/PreviewerActions/index.tsx
src/client/theme-default/slots/SourceCodeEditor/index.tsx
src/loaders/markdown/index.ts
src/loaders/markdown/transformer/index.ts
src/loaders/markdown/transformer/rehypeDemo.ts
src/techStacks/react.ts
src/types.ts

#1922 
支持自定义技术栈实现 live demo 特性，主要改动点：
1. `techStack` 类新增 `runtimeOpts` 属性，声明 `compilePath` 指向运行时编译 demo 的函数模块即可，该模块需要 default 导出编译函数，dumi 会在用户编辑 demo 时自动按需加载它
2. 没有声明 `compilePath` 的自定义技术栈代表不支持 live demo，dumi 不会为对应 demo 展示编辑态
3. 内置的 React 技术栈也重构为同样的 `runtimeOpts` 属性模式，并将 `SourceCodeEditor` 中的代码编译逻辑挪到 `useLiveDemo` API 中，减少开发者/用户覆盖 `SourceCodeEditor` 的成本
4. `useLiveDemo` API 新增 `loading` 状态，Vue 技术栈目前的 compile 模块产物较大，超过 500ms 没编译成功则会展示 loading 态
cc @jeffwcx 

feat: live demo support custom tech stack

---

src/features/compile/index.ts
src/loaders/markdown/index.ts

https://github.com/umijs/dumi/pull/1649
https://github.com/umijs/dumi/pull/1659
md-loader 在生产构建且应用启用资产元数据相关能力时禁用缓存，以避免命中 webpack loader 缓存 -> hook 不执行 -> 资产元数据缺失 -> 相关能力异常
仅在 prod 开启是因为 dev 禁用 loader 缓存会影响编译性能，且 dev 场景下用户不直接消费资产元数据，在准确性和性能中选择了后者
| 🇺🇸 English | Fix assets metadata lost bug when enable fs cache |
| 🇨🇳 Chinese | 修复启用持久缓存时资产元数据可能丢失的问题 |

fix: assets metadata may lost when enable fs cache in prod

---

src/client/pages/Demo/index.ts
src/client/theme-api/useLiveDemo.ts
src/client/theme-default/builtins/Previewer/index.tsx
src/loaders/markdown/index.ts

无
将 iframe demo 的通信逻辑集成到 `useLiveDemo` 的实现中，外部不再关心通信的细节，只需要把 iframe 的父级 DOM ref 扔进去，该改动可降低自定义主题的开发者使用 `useLiveDemo` 及覆写 `Previewer` 的成本。
另外顺便做了两个优化：
1. demo context 不再包含 demo entry 自己，这会导致产物出现重复（因为 demo 有 techStack 的 require query，webpack 会认为是两个不同的模块）
2. 在 `useLiveDemo` 的异步 chunk 加载过程中如果 pending 了多个编译任务，在 chunk 加载完成后 `useLiveDemo` 会跳过已经过期的任务
cc @MadCcc antd 又要改一波了 👀 

feat: useLiveDemo support iframe demo

---

src/client/theme-api/useRouteMeta.ts
src/client/theme-api/utils.ts
src/features/exports.ts
src/templates/meta/exports.ts.tpl

https://github.com/ant-design/ant-design/issues/47058
修复 `useRouteMeta` 引发意外 suspense 导致出现不必要的 loading 状态的问题，这也会导致 `Helmet` 工作不正常，比如 Ant Design 官网在路由切换时网页标题可能不会更新

fix: unexpected suspense from useRouteMeta

---

src/features/compile/index.ts
src/types.ts

无
自定义技术栈支持声明关联的运行时插件，该插件通常用来定义与技术栈对应的自定义运行时配置（比如 `modifyCodeSandboxData` 等），是比 `api.addRuntimePlugin` 关联性更高的注册方式，未来也可能会用于框架识别技术栈的运行时能力（比如是否支持在 CodeSandbox 中打开）
cc @jeffwcx 

feat: tech stack supports declare runtime plugin

---

examples/normal/.dumirc.ts
src/client/theme-default/builtins/SourceCode/index.less
src/client/theme-default/builtins/SourceCode/index.tsx
src/client/theme-default/slots/SourceCodeEditor/index.less
src/client/theme-default/slots/SourceCodeEditor/index.tsx

close https://github.com/ant-design/ant-design/issues/46992
由于代码展示和编辑分别由两个不同的元素完成，如果要同时滚动的话可能做虚拟滚动会好些，成本略高。
简单套用 react-simple-code-editor 的方式让代码换行。
| 🇺🇸 English |     Fix SourceCode that cannot scroll.      |
| 🇨🇳 Chinese |    修复 SourceCode 无法滚动的问题。       |

fix: overflow for source code editor

---

src/client/theme-default/slots/SourceCodeEditor/index.less

close https://github.com/ant-design/ant-design/issues/47230
代码可以滚动时滚动条被 focus 的伪类挡住了，无法拖拽。处理一下伪类。
| 🇺🇸 English |  Fix code editor that scroll bar couldn't be dragged.         |
| 🇨🇳 Chinese |     修复代码编辑器滚动条无法拖拽的问题。      |

fix: code editor scroll bar should be draggable

---

scripts/sync-from-umi.js

修复 Umi 文档同步脚本，去掉 `HashAnchorCompat` 全局 anchor 兼容组件

docs: fix umi docs sync script

---

scripts/sync-from-umi.js

我本地还是遇到和去年反馈的问题一样，本地同步 umijs 文档经常失败
**使用 GitHub raw**
同步遇到 443 失败时, 可以尝试 `SYNC_USE_GITHUB=1 npm run docs:sync` 使用 GitHub 作为源
**本地启动服务**
本地 clone 了 umijs 仓库，使用 http-server启动服务，`SYNC_CUSTOM_UPSTREAM=http://127.0.0.1:8080/ npm run docs:sync`
| 🇺🇸 English |     Improve document synchronization logic and support source switching      |
| 🇨🇳 Chinese |    改进文档同步逻辑，支持切换源       |

chore: update docs sync source

---

docs/config/index.md
docs/guide/vue-api-table.md
docs/guide/vue.md
docs/plugin/api.md
docs/plugin/techstack.md

更新vue技术栈相关文档
| 🇺🇸 English |    update vue tech stack related documents       |
| 🇨🇳 Chinese |     更新vue技术栈相关文档      |

docs: describe for vue tech stack

---

docs/guide/vue-api-table.md
docs/guide/vue.md
docs/plugin/market.md
docs/plugin/techstack.md

Vue 使用补充说明
| 🇺🇸 English |  vue usage supplement explanation  |
| 🇨🇳 Chinese |  vue 使用补充说明   |

docs: vue usage supplement explanation

---

src/client/theme-api/useLiveDemo.ts
src/constants.ts
src/features/compile/index.ts

…p error
| 🇺🇸 English |    reslove conditionNames just for commonjs and supplement prod skip err       |
| 🇨🇳 Chinese |    resolve 条件名只针对commonjs 并增加livedemo 生产环境需要跳过处理的错误类型       |

fix: non-cjs module may be unexpectedly resolved due to wrong conditions

---

.npmrc
src/client/theme-default/slots/Toc/index.tsx

fix https://github.com/umijs/dumi/issues/2007
由于header 的布局是`sticky`, 当点击左侧sidebar时，`核心 API` 这个锚点内容还是处于可视状态，即`currentElementIndexInViewport` 还是在当前的key中， 所以这里需要用-offset (header的高度)，触发它的激活状态

fix: active position for toc scrolling highlight

---

src/assetParsers/block.ts

| 🇺🇸 English | skip resolveMap handle when runtimeOpts not exists    |
| 🇨🇳 Chinese |  runtimeOpts不存在时不需要处理resolveMap         |

fix: skip resolveMap handle when runtimeOpts not exists

---

src/client/theme-api/useRouteMeta.ts

fix: duplicated features in frontmatter

---

src/templates/meta/exports.ts.tpl

refactor: getMetaByRouteId return metainfo for all routes

---

src/client/theme-default/builtins/API/index.tsx

Since #1922
修复 API 表格不传递 type 时默认值列始终不会展示的问题
| 🇺🇸 English | Fix default column lost bug for API table |
| 🇨🇳 Chinese | 修复 API 表格默认值列丢失的问题 |

fix: default column lost bug for API table

---

src/client/theme-api/useRouteMeta.ts
src/templates/meta/exports.ts.tpl

#2134 引入问题
1. 所有路由都返回 routeMeta 会导致路由表错乱, 首页 redirect 到404 页面, 回滚变更, 不触发 useRouteMeta 的 merge 逻辑.
2. 修复 ayncCache 遇到用户插件自定义 meta 导致的异常错误.
| 🇺🇸 English |  fallback useRouteMeta logic and handle errors caused by custom routeMeta         |
| 🇨🇳 Chinese |   回滚 useRouteMeta 变更 & 解决用户自定义 meta导致的异常  |

fix: fallback useRouteMeta logic and handle errors caused by custom routeMeta

---

docs/guide/markdown.md
src/client/theme-default/builtins/Tree/index.tsx

https://github.com/umijs/dumi/issues/2071
tree支持空 ul 也判定为文件夹
| 🇺🇸 English |    The tree structure also treats empty ul as a folder       |
| 🇨🇳 Chinese |      Tree支持空 ul 也判定为文件夹     |

feat: builtin Tree component can recognizes empty ul as a folder

---

src/features/compile/index.ts
src/templates/meta/exports.ts.tpl

| 🇺🇸 English |    mako feature query watch = parent make some techStack crash when webpack build       |
| 🇨🇳 Chinese |     mako 特性 watch = parent 影响到了某些技术栈webapck构建     |

fix: mako feature query watch=parent make some techStack crash when webpack build

---

docs/theme/api.md
src/client/theme-api/index.ts
src/client/theme-api/useRouteMeta.ts

fix: #2124
https://github.com/umijs/dumi/pull/1974 中对 useRouteMeta 返回结果进行了 Proxy , 并且在获取 texts 时抛出了一个 Promise
[dumi-theme-antd-style](https://github.com/arvinxx/dumi-theme-antd-style/) 主题包在 https://github.com/arvinxx/dumi-theme-antd-style/blob/7d6977a374a21be7399492522439e8005a7f7fda/src/components/StoreUpdater/index.tsx#L74 处引用了，导致页面一直卡白屏（未处理 Promise）.
主题侧准备 [用 SWR 自定义获取 RouterMeta](https://github.com/arvinxx/dumi-theme-antd-style/pull/122/files#r1612952871) 但是需要获取当前 router.id  并通过 dumi 的 `getRouteMetaById` 方法获取 meta 信息。
将逻辑提取为 `useMatchedRoute` 并对外暴露出来。
| 🇺🇸 English |     export `useMatchedRoute` feature hooks      |
| 🇨🇳 Chinese |      导出`useMatchedRoute` hooks     |

feat: export useMatchedRoute hook for theme

---

src/client/theme-default/slots/SourceCodeEditor/index.tsx

在编辑时，如果浏览器开启了拼写错误检查，会在一些单词上出现红色波浪线，这个应该是没有必要的，直接禁用它，后面有需求可以考虑传递参数开启。

feat(editor): disable spellcheck

---

package.json
src/client/theme-default/slots/SourceCodeEditor/index.tsx
src/features/compile/index.ts
src/loaders/markdown/index.ts

#2185 
#2183 
修改`cjs` resolve 存在太多问题, 这里不再改变用户源码导入规则.
遗留action: 目前全部采用`import * as` 导入,  `webpack` 与`mako` 对 `interop` 的处理目前来看存在差异, 之后遇到了再解决.
| 🇺🇸 English |   liveDemo context no longer uses require for imports        |
| 🇨🇳 Chinese |    liveDemo context 不再使用`require` 导入替换用户源码`imports `      |

refactor: liveDemo context no longer uses require for imports

---

src/loaders/markdown/index.ts

demo 共享 deps, 引入相对路径时, 忽略了相对路径可能最终 resolve 的 path 是一致的, 对于这种情况也需要共享, 否则依赖引入会缺失.
| 🇺🇸 English |    demo relative path also need to share       |
| 🇨🇳 Chinese |   demo 共享相对路径引入依赖        |

fix: demo relative path also need to share

---

src/loaders/markdown/index.ts

Minimal Reproduction / 最小复现：
https://github.com/wzc520pyfm/dumi-relative-path-test
Using the relative path `..` in the demo will result in a parsing error:
demo中使用相对路径`..`会解析错误：
However, this works fine in 2.4.7.
然后，它在2.4.7中是正常工作的。
```tsx
import Foo from '..'
```
Solution / 解决方式：
`..` should be recognized as a relative path.
`..` 应该被识别为相对路径。
| 🇺🇸 English |  fix relative path (`..`) parsing error |
| 🇨🇳 Chinese |  修复相对路径`..`解析错误  |

fix: relative import of `.` & `..` parsing error

---

docs/guide/faq.md
src/features/compile/index.ts
src/features/compile/makoHooks.ts
src/features/compile/utils.ts
src/loaders/markdown/index.ts

#2193 
用户配置按需加载后, `babel-plugin-import` 会擦除 `dumi` 注入 `livedemo context `的相关 `import * as` 语句, 导致 `context` 内的变量未定义
why 禁用 ?
浏览器用户源码编译是不经过 `babel-plugin` 处理的, 目前也没有必要改变这一现状.
禁用一不会报错, 二不会影响存量用户.
| 🇺🇸 English |    livedemo disabled when config babel-plugin-import        |
| 🇨🇳 Chinese |    配置按需加载后禁用liveDemo       |

fix: livedemo disabled when config babel-plugin-import

---

src/client/theme-default/builtins/API/index.tsx

- Resolved logic errors when processing fixed-length tuple types such as [number, number].
- Enhanced type inference to ensure accurate handling of array types during component generation.
This update improves the compatibility and stability of auto API components with complex array types.
在之前的版本中，自动 API 表格组件在处理固定长度的元组类型（例如 [number, number]）时，会错误地将其识别为 unknown[] 类型。
In the previous version, the auto API table component incorrectly treated fixed-length tuple types (e.g., [number, number]) as unknown[].
| 🇺🇸 English |  Fix handling of specific array types in auto API components  |
| 🇨🇳 Chinese |  修复自动 API 组件中特定数组类型的处理问题 |

fix: Fix handling of specific array types in auto API components
