umijs/dumi

packages/umi-plugin-father-doc/src/index.ts
~~塑料同事情~~
我就想安安稳稳写个文档，桃子兄你是怎么做到每次更新都送我一个新的 crash 礼包的？
低级错误，不想赘述
有多种处理方式，选择这里下手是从这样更符合 ts 类型定义
既不开 `strictNullChecks `，又不开 `noImplicitAny`，那 TS 还检查个🔨 哦
=> fix: userExtraBabelPlugin is not iterable

packages/umi-plugin-father-doc/src/themes/default/layout.less, packages/umi-plugin-father-doc/src/themes/default/layout.tsx
=> site: better responsive

packages/umi-plugin-father-doc/src/index.ts
- change pkgPath to pkgPath/src
-  mkdir link  pkg to node_modules/pkg
=> feat: add lint to fix tsconfig and eslint no reslove

packages/umi-plugin-father-doc/src/routes/decorator/fallback.ts, packages/umi-plugin-father-doc/src/routes/decorator/index.ts, packages/umi-plugin-father-doc/src/routes/decorator/locale.ts, packages/umi-plugin-father-doc/src/routes/decorator/redirect.ts, packages/umi-plugin-father-doc/src/routes/getRouteConfig.ts, packages/umi-plugin-father-doc/src/routes/getRouteConfigFromDir.ts, packages/umi-plugin-father-doc/src/themes/default/layout.less, packages/umi-plugin-father-doc/src/themes/default/layout.tsx
* 修复了 window 下 index.md 不会生成 '/' 的问题
* 修了几个lint
=> bugfix: Fix the problem of homepage judgment error under window

config/config.js, now.json
+  只上传静态文件，不使用 now 来构建
+  构建结果增加 hash (为下一步作准备)
+ 为 css js 文件增加缓存
=> :zap: change now config to improving build performance.

docs/guide/faq.md
Resolve https://github.com/umijs/dumi/issues/130
=> docs: github page faq

packages/preset-dumi/src/routes/getMenuFromRoutes.ts
=> refactor: rewrite menu sorter

docs/demo/users.tsx, packages/dumi/README.md
=> Add Remax in users

packages/preset-dumi/src/themes/default/layout.less
=> style: tweak features font size

docs/config/index.md, packages/preset-dumi/src/index.ts, packages/preset-dumi/src/plugins/algolia.ts, packages/preset-dumi/src/plugins/core.ts, packages/preset-dumi/src/themes/default/SearchBar.less, packages/preset-dumi/src/themes/default/SearchBar.tsx, packages/preset-dumi/src/themes/default/SearchBar/algolia.tsx, packages/preset-dumi/src/themes/default/SearchBar/default.tsx, packages/preset-dumi/src/themes/default/context.ts, packages/preset-dumi/src/themes/default/layout.tsx
https://docsearch.algolia.com
测试配置
```js
algolia: {
apiKey: 'f86a1d257e40b994bc656299b53fecf6',
indexName: 'remaxjs',
debug: true
}
```
=> feat: 新增 algolia 的 docsearch 支持

docs/demo/users.tsx, packages/dumi/README.md
=> doc: make icon of lightproxy more umi

packages/preset-dumi/src/transformer/index.ts
=> fix: https://github.com/umijs/umi/issues/4688

config/config.js, docs/guide/seo.md
=> docs: seo document

docs/guide/faq.md
add how to dynamic import css in md file.
=> docs: faq add how to dynamic import css in md file

docs/demo/show-preview.tsx, docs/examples.md, packages/preset-dumi/src/themes/default/builtins/Previewer.tsx, packages/preset-dumi/src/transformer/remark/previewer.ts
Fixes #
代码片段关于按钮的设置不知道如何设计修改，另外transform中目前ast解析对于类似md文件中标签 isShow={false} 语法不支持，是否考虑 fix。
=> chore: add demo preview and codesandbox button configuration

docs/guide/faq.md
添加FAQ：dumi 如何支持对 swift、C#、Kotlin等语言的语法高亮？
=> docs: add faq with prism-react-renderer

.github/ISSUE_TEMPLATE/feature_request.md
=> chore: update issue template typo

docs/demo/users.tsx
=> chore: users styles

packages/preset-dumi/src/transformer/remark/meta.ts
=> fix: yaml no data error

packages/dumi/README.md
=> docs: improve grammar for README.md

packages/theme-default/src/components/Navbar.less, packages/theme-default/src/components/Navbar.tsx, packages/theme-default/src/components/SideMenu.less, packages/theme-default/src/components/SideMenu.tsx
=> fix(theme): avoid validateDOMNesting errors,fix #390

docs/config/frontmatter.md, docs/config/frontmatter.zh-CN.md, docs/index.md, packages/theme-default/src/layout.tsx, packages/theme-default/src/style/layout.less
close https://github.com/umijs/dumi/issues/393
新增首页标题配图
=> feat: add hero image

packages/create-dumi-app/templates/AppGenerator/.gitignore.tpl, packages/create-dumi-lib/templates/AppGenerator/.gitignore.tpl
=> style: 💄 向 gitignore 模板中增加忽略编辑器自带文件项

docs/guide/advanced.md, docs/guide/advanced.zh-CN.md
- 英文版
- 进阶使用
- 中文增加了 locales 链接
- 有个 2 级标题下，直接跟了 4 级，我改成 3 级了，不知道是不是有意为之
https://github.com/umijs/dumi/pull/419
=> docs: add advanced en

docs/theme/api.md, docs/theme/api.zh-CN.md, docs/theme/development.md, docs/theme/development.zh-CN.md, docs/theme/index.md
- 英文版
- 主题列表
- 主题开发
- 主题 API
https://github.com/umijs/dumi/pull/419
=> docs: add theme en

docs/lab/index.md, docs/lab/index.zh-CN.md
- 英文
- 实验室
https://github.com/umijs/dumi/pull/419
=> docs: add lab en

docs/plugin/index.md, docs/plugin/index.zh-CN.md
- 英文
- 插件
https://github.com/umijs/dumi/pull/419
=> docs: add plugin en

.github/PULL_REQUEST_TEMPLATE.md
none
none
| 🇺🇸 English |  Add PR template.         |
| 🇨🇳 Chinese | 新增 PR 模板。          |
=> docs: add pr temp

packages/create-dumi-app/templates/AppGenerator/tsconfig.json, packages/create-dumi-lib/templates/AppGenerator/tsconfig.json
https://github.com/umijs/father/issues/286
=> perf: tsconfig exclude

docs/config/frontmatter.md, docs/config/frontmatter.zh-CN.md, docs/index.md, packages/theme-default/src/layout.tsx, packages/theme-default/src/style/layout.less, packages/theme-default/src/style/markdown.less, packages/theme-default/src/test/index.test.tsx
close https://github.com/umijs/dumi/issues/436
点击 title 进行跳转
1. Link
增加链接后，使用了默认主色。交互方式同 其他 link
主页的链接 供 观察效果，确定后再移除
2. css
优化一点 css，markdown a 标签已增加了 color， hover active color 重复
| 🇺🇸 English | Add Feature Link.          |
| 🇨🇳 Chinese |  新增 Feature 链接功能。         |
=> feat: add feature link

packages/theme-default/src/layout.tsx, packages/theme-default/src/test/index.test.tsx
…ate click event
修复全局代理事件导致应用重绘的问题
=> fix(theme-default): fix application always rerender from global delegate click event.

docs/config/frontmatter.md
=> docs: add frontmatter

packages/theme-default/src/components/Navbar.less
当只有 search 框和 语言切换时，间隔缺失
| 🇺🇸 English | Fix the missing space between search input and language switch.  |
| 🇨🇳 Chinese | 修复搜索框和语言切换缺失间隔的问题。          |
=> fix: search + change miss space

docs/guide/index.md
=> docs: add Introducation

docs/config/index.md
=> docs: add config of en version

docs/guide/advanced.zh-CN.md
=> docs: Update advanced.zh-CN.md

docs/index.md, docs/index.zh-CN.md, scripts/update-readme-user.js
合并到 #463 
修改 dumi 用户表格的引入方式，从行数引入变成正则表达式匹配引入，该引入方式为 `embed` 标签的新增使用方式，可替换掉原有脚本中改动行号的逻辑。
其他变更：prettier 脚本代码
| 🇺🇸 English |  --       |
| 🇨🇳 Chinese |  --       |
=> chore: use regexp for embed users in homepage

docs/config/index.zh-CN.md
无
补充 https://github.com/umijs/dumi/pull/477
| 🇺🇸 English |  fix the title level in config.zh-CN  |
| 🇨🇳 Chinese |   修复配置项中文页面标题层级问题        |
=> docs: fix config title level in Chinese

packages/preset-dumi/src/transformer/remark/meta.ts
修复在 index.xx-xx.md 中使用 `<API></API>` 不写 src，没有自动匹配到组件的问题。
| 🇺🇸 English | fix get componentName error |
| 🇨🇳 Chinese | 修复自动获取组件名称错误的 bug |
=> fix: get componentName error

packages/dumi/README.md, scripts/update-readme-user.js
占个广告位
| 🇺🇸 English |     add user alita      |
| 🇨🇳 Chinese |    添加用户 alita       |
=> chore: add user alita

docs/config/frontmatter.md, docs/config/frontmatter.zh-CN.md, packages/preset-dumi/src/loader/fixtures/customize.md, packages/preset-dumi/src/loader/fixtures/normal.md, packages/preset-dumi/src/loader/index.test.ts, packages/preset-dumi/src/loader/index.ts
| 🇨🇳 Chinese |  扩展 translateHelp 类型，String 可自定义翻译提示语内容。          |
=> feat: expand translateHelp type

packages/preset-dumi/src/utils/getFileContent.ts
=> fix(preset): content split when use embed

packages/theme-default/src/layout.tsx
=> fix(theme-default): add space between updatedDate  and updatedTime

packages/theme-default/src/components/Navbar.less, packages/theme-default/src/components/SideMenu.less
https://qiankun.umijs.org/
- nav 多个时 颜色不一致
| 🇨🇳 Chinese |  修复 nav 设置多个时颜色不一致的问题。         |
=> fix(theme): multiple nav text color

packages/theme-default/src/style/layout.less
=> perf(theme): optimize features style

.github/workflows/pr-welcome.yml
=> ci: add pr welcome action

packages/preset-dumi/src/utils/getHostPkgAlias.ts
lerna4 报错
Error: Cannot find module 'lerna/lib/PackageUtilities'
| 🇺🇸 English |     support lerna4      |
| 🇨🇳 Chinese |     支持  lerna4    |
=> fix(preset-dumi): support lerna4

packages/preset-dumi/package.json
=> fix: cannot find module sitemap

jest.config.js, packages/preset-dumi/src/transformer/fixtures/expect/remark-basic.html, packages/preset-dumi/src/transformer/fixtures/expect/remark-demo.html, packages/preset-dumi/src/transformer/remark/sourceCode.ts
| 🇺🇸 English |      移除多余尾行    |
| 🇨🇳 Chinese |       remove redundant  empty line   |
=> fix: drop unexpect source code empty line

docs/guide/faq.md, docs/guide/faq.zh-CN.md
=> fix(docs): REAdME.md -> README.md

packages/preset-dumi/src/utils/getRepoUrl.test.ts, packages/preset-dumi/src/utils/getRepoUrl.ts
https://github.com/umijs/dumi/issues/562#issuecomment-803723546
| 🇨🇳 Chinese | Gitlab 子组跳转 URL 支持 http 协议。            |
=> feat: gitlab subgroups support http protocol

docs/guide/faq.md, docs/guide/faq.zh-CN.md
| 🇨🇳 Chinese |  新增 repository 配置介绍。         |
=> docs: add repository config introduce

docs/guide/faq.md, docs/guide/faq.zh-CN.md, packages/preset-dumi/src/plugins/features/demo/index.ts
| 🇺🇸 English |  config/config.js  ->  dumi/config/config.js        |
| 🇨🇳 Chinese |   config/config.js  ->  dumi/config/config.js      |
=> docs: 文档，非 umi 项目配置文件目录

docs/guide/faq.md, docs/guide/faq.zh-CN.md
#603 
合并了非根目录部署和GitHub Pages部署的场景下的FAQ文档及配置细节。
| 🇺🇸 English | merge FAQ documents of non-root deployment and Github Pages deployment |
| 🇨🇳 Chinese | 合并非根目录部署和GitHub Pages部署场景下的FAQ文档 |
=> docs: optimize faq guide (fix #603)

packages/preset-dumi/src/routes/decorator/redirect.ts, packages/preset-dumi/src/routes/test/redirect.test.ts
#610 
- 通过用户配置项中拿到的左侧菜单栏，有可能存在首个就是有效路由，不必要去拿 `children` 来当重定向路由
- 和 `Nav` 的重定向路由类似，`Menu` 的重定向路由的获取同样也从用户配置项的 `Menu` 对象中获取
| 🇺🇸 English |  improve redirct route for group which has no index route         |
| 🇨🇳 Chinese |   优化没有首页的菜单及导航的重定向路由        |
=> fix(routes): 优化没有 index 的菜单及导航的重定向路由

packages/dumi/README.md, scripts/update-readme-user.js
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |      -     |
=> docs: perf users show

packages/preset-dumi/src/plugins/features/config.ts, packages/preset-dumi/src/utils/getRepoUrl.ts
当 package.json 如下设置 启动报错 
```
{
"repository": {
},
}
```
| 🇨🇳 Chinese |   修复 package 里 repository 设置空对象时启动报错的问题。        |
=> fix: repository empty object start error

packages/theme-default/src/style/layout.less
| 🇨🇳 Chinese | 修复 footer 里编辑代码跳转按钮 hover 交互样式缺失。          |
=> fix: footer a hover style

scripts/sync-from-umi.js
=> docs: fix sync api doc

packages/preset-dumi/src/transformer/demo/dependencies.ts
修复在 codesandbox 中，没有引入 css 的问题。因为在真实的项目中不需要引入，所以在这里统一添加。
=> chore: fix pro-component css loase on codesandbox

packages/theme-default/src/builtins/SourceCode.less
背景：深色模式下未设置代码选中颜色
解决方案：深色模式下设置代码选中颜色为黑色
解决的具体问题：深色模式下，未设置代码选中颜色体验不太好
=> feat(theme): set code selection color in dark mode

packages/preset-dumi/src/theme/hooks/useSearch.ts, packages/theme-default/src/components/SearchBar.less
=> improvement: 去除搜索结果数量限制

packages/dumi/README.md, scripts/update-readme-user.js
- [ √ ] 网站、文档、Demo 改进 / Website, documentation, demo improvements
add a demo using dumi.
add a demo called react-org-tree.
=> add a site using dumi

packages/preset-dumi/src/routes/decorator/fallback.ts
README.md 文件的自定义 FrontMatter 不生效
| 🇺🇸 English |  修复 README.md 文件的自定义 FrontMatter  |
| 🇨🇳 Chinese | Fix custom FrontMatter for README.md file |
=> fix: custom meta when no index

.github/workflows/issue-reply.yml
fix generate url
体验优化：说了点击此处创建，其实跳转之后，还要点击使用模版。
=> fix generate url

.github/workflows/ci-notice.yml
=> ci: create ci notice

packages/theme-default/package.json, packages/theme-mobile/package.json
none.
解决npm v7以后对peerDependencies的处理，兼容react17版本.
=> fix(package): support react^17.0.0 version

packages/preset-dumi/src/plugins/features/theme.ts
close https://github.com/umijs/dumi/issues/811
| 🇨🇳 Chinese |  使用 indexOf 兼容 IE          |
=> style: change includes to indexOf

docs/guide/basic.md, docs/guide/basic.zh-CN.md
=> docs: recommend using `TS in Markdown Visual Studio extension`

packages/theme-default/src/components/Navbar.less, packages/theme-default/src/components/SideMenu.less
| 🇨🇳 Chinese | 优化 Dark 模式样式。          |
=> style(theme): optimize dark theme

docs/guide/advanced.md, docs/guide/advanced.zh-CN.md, packages/preset-dumi/src/transformer/fixtures/remark-api/alias.md, packages/preset-dumi/src/transformer/remark/api.ts, packages/preset-dumi/src/transformer/test/remark-api.test.ts
| 🇺🇸 English |   `API` component `src` supports use `alias` |
| 🇨🇳 Chinese |   API 组件 `src` 支持使用 `alias` |
=> feat(theme): support use alias path in API component

packages/theme-default/src/components/SearchBar.less
| * | * |
| -- | -- |
| Before |  ![image](https://user-images.githubusercontent.com/29775873/130481108-9c253ddb-1152-4265-a2ef-78b3acab1ba1.png) |
| After | ![image](https://user-images.githubusercontent.com/29775873/130481234-e84cd487-cfc7-48af-8ddf-59ab57820fd1.png) |
| 🇨🇳 Chinese | mobile 模式下 隐藏 input 非 focus value 显示          |
=> fix(theme): hide input value in mobile search

packages/preset-dumi/src/transformer/fixtures/expect/remark-img.html, packages/preset-dumi/src/transformer/fixtures/raw/remark-img.md, packages/preset-dumi/src/transformer/remark/img.ts
#865
img.src 使用 decodeURI 解码
| 🇺🇸 English |  img.src apply decodeURI   |
| 🇨🇳 Chinese |  img.src 使用 decodeURI 解码 |
=> fix(transformer):  img.src apply decodeURI

packages/preset-dumi/src/transformer/fixtures/remark-api/Hello/index.d.ts, packages/preset-dumi/src/transformer/fixtures/remark-api/guess-name.md, packages/preset-dumi/src/transformer/remark/api.ts, packages/preset-dumi/src/transformer/test/remark-api.test.ts
#882 
#882 
| 🇺🇸 English |     fix API parse .d.ts file path      |
| 🇨🇳 Chinese |     修复API解析.d.ts文件路径问题      |
=> fix(preset): guess declaration filename

docs/theme/index.zh-CN.md
=> feat: add dumi-theme-tuya

docs/guide/index.md, docs/guide/index.zh-CN.md
=> fix: update build command in docs

docs/.demos/modal/modal.jsx
用函数式组件和hook的方式重写`/docs/.demos/modal/modal.jsx`
| 🇺🇸 English |  use functional component and hooks to rewrite modal.jsx in demo  |
| 🇨🇳 Chinese |  将demo里的modal.jsx替换为函数式组件 |
=> fix: use hook to rewrite demo model.jsx

docs/theme/index.zh-CN.md
=> docs: The lack of "rules"

packages/preset-dumi/src/transformer/remark/img.ts
=> fix: support blob:protocol:// as img url

docs/guide/advanced.md, docs/guide/advanced.zh-CN.md, packages/preset-dumi/src/theme/hooks/useApiData.test.tsx, packages/preset-dumi/src/theme/hooks/useApiData.ts
- close #1055
#1055 
API 表格 description 字段多语言缺失时，使用默认语言兜底
=> feat: API table description cover

packages/dumi/README.md, scripts/update-readme-user.js
=> docs:add XRender in users

packages/preset-dumi/src/utils/getHostPkgAlias.ts
#
pnpm monorepo 场景下 demo dependencies 收集错误，导致打开 codeSandbox 缺少相应 dep
│ ── package.json
│ ── packages
│  └─ pkg1
│  └─ pkg2
按目前 [getHostPkgAlias](https://github.com/umijs/dumi/blob/master/packages/preset-dumi/src/utils/getHostPkgAlias.ts#L50) 的逻辑，获取的是 host pkg
| 🇺🇸 English |    dep collect bug for host pkgs in pnpm workspace       |
| 🇨🇳 Chinese |   pnpm workspace 场景下依赖收集错误       |
=> fix(preset): dep collect bug for host pkgs in pnpm workspace

packages/preset-dumi/src/theme/hooks/useCodeSandbox.ts, packages/preset-dumi/src/transformer/demo/dependencies.ts
=> fix: fix injectReact formart node work error

docs/guide/faq.md, docs/guide/faq.zh-CN.md
=> docs: replace for details, see url

docs/guide/index.md, docs/guide/index.zh-CN.md
调整文档中的命令
Adjusting commands in a document
暂无issue
对文档中的 开始开发 部分做出一些调整
| 🇺🇸 English |     Adjusting commands in a document      |
| 🇨🇳 Chinese |     调整文档中的命令      |
=> docs: update index.zh-CN.md

.gitignore, .prettierrc.js, package.json
更新 prettier 配置方式  兼容 `vscode` 插件
=> chore: update prettier conf

src/features/compile.ts, src/loaders/markdown/index.ts
=> feat: support md file hot update

docs/config/index.md, docs/config/index.zh-CN.md
=> docs: add navs rule note

src/features/compile.ts
=> feat: fastRefresh is handled by the development only

packages/preset-dumi/src/theme/hooks/useCodeSandbox.ts
=> fix: modify the codesandbox default description

src/features/theme/index.ts
=> chore: fix comment syntax

package.json
复现步骤，
```bash
$ pnpm i dumi@beta -D
```
=> fix: postinstall > prepare, fix install problem

package.json, pnpm-lock.yaml, src/features/meta.ts
=> deep meta-data merging

package.json, pnpm-lock.yaml, src/loaders/markdown/index.ts, src/loaders/markdown/transformer/index.ts, src/utils.ts
Markdown transformer 增加持久缓存
| 🇺🇸 English |     add markdown transformer cache      |
| 🇨🇳 Chinese |    增加 markdown transformer 缓存       |
=> feat: add markdown transformer cache

src/client/theme-default/builtins/Previewer/index.less, src/client/theme-default/builtins/Previewer/index.tsx, src/client/theme-default/slots/PreviewerActions/index.less, src/client/theme-default/slots/PreviewerActions/index.tsx, src/client/theme-default/slots/PreviewerActionsExtra/index.tsx
1）抽离 Previewer 的 actions，支持通过 props 传递 disabledActions 来禁用指定action
2）添加 PreviewerActionsExtra，支持扩展 action
=> feat: pull out the previewe actions

docs/guide/upgrading.md
=> docs: update upgrading docs

src/features/compile.ts, src/features/theme/index.ts, src/loaders/markdown/transformer/index.ts, src/loaders/markdown/transformer/rehypeLink.ts
- 站内链接使用 Link 标签
- 支持链接到 md
| 🇺🇸 English |    handle link in md       |
| 🇨🇳 Chinese |   处理 link        |
=> feat: handle link in md

src/client/theme-default/slots/Navbar/index.tsx
#1255
| 🇺🇸 English |     handle outside links with `a` tag      |
| 🇨🇳 Chinese |    handle outside links with `a` tag       |
=> fix(Navbar): handle outside links with `a` tag

src/assetParsers/block.ts
修复 demo 出现语法错误后不会再监听文件变动       
| 🇺🇸 English |      fix demo syntax error will block watch     |
| 🇨🇳 Chinese |    修复 demo 出现语法错误后不会再监听文件变动       |
=> fix: demo syntax error will block watch     

package.json, pnpm-lock.yaml, src/client/theme-api/index.ts, src/client/theme-api/openStackBlitz.ts, src/client/theme-default/locales/en-US.json, src/client/theme-default/locales/zh-CN.json, src/client/theme-default/slots/PreviewerActions/index.tsx
| 🇺🇸 English |    support open in stackblitz       |
| 🇨🇳 Chinese |   支持在 stackblitz 中打开        |
=> feat: support open in stackblitz

src/client/theme-default/builtins/SourceCode/index.less
为复制按钮提升z-index/也可以将SourceCode中CopyToClipboard组件下移到Highlight组件
| 🇺🇸 English |fixed invalid copy button|
| 🇨🇳 Chinese |修复-复制按钮失效的问题|
=> fix(SourceCode): fixed invalid copy button

package.json
补充一些包基础属性。
| 🇺🇸 English |   --        |
| 🇨🇳 Chinese |   --        |
=> chore: fill package.json fields

docs/guide/index.md, src/client/theme-default/slots/Content/index.less
https://github.com/umijs/dumi/discussions/1216#discussioncomment-4157279
markdown图片宽度超出
修复前：
修复后：
=> fix: markdown-image-width-exceeds

src/features/meta.ts
https://github.com/umijs/dumi/issues/1291
使用winPath方法对路径进行转换。
| 🇺🇸 English | fix wrong path of generated code in Windows |
| 🇨🇳 Chinese | 修复Windows环境下，生成代码的路径异常问题 |
=> fix: wrong path of generated code in Windows

docs/guide/upgrading.md
=> docs: demo single label changed to double label

src/client/theme-api/useSiteSearch/index.ts, src/client/theme-default/slots/SearchBar/Input.tsx, src/client/theme-default/slots/SearchBar/Mask.tsx, src/client/theme-default/slots/SearchBar/index.less, src/client/theme-default/slots/SearchBar/index.tsx, src/client/theme-default/slots/SearchResult/index.tsx
#1290 
| 🇺🇸 English |    open search modal when search bar is not in viewport       |
| 🇨🇳 Chinese |   搜索框不在可见区域时打开搜索弹框        |
=> feat: open search modal when search bar is not in viewport

src/loaders/markdown/transformer/rehypeDemo.ts
=> fix(code-block): 修复 codeBlock 编译 tsx 报错的问题

package.json, pnpm-lock.yaml, src/client/theme-api/DumiPage.tsx, src/client/theme-default/slots/Toc/index.tsx
基于此条新增Toc的pr，在原有Toc组件基础上增加滚动过渡效果。
https://github.com/umijs/dumi/pull/1295
采用 提前计算落差高度，通过`requestAnimationFrame` 一次动画执行35次完成过渡。
=> feat: Toc component scroll transition when click

src/client/theme-default/slots/SearchBar/index.less
搜索内容超长时，没有滚动条
修复后
搜索弹窗内容超长时，没有滚动条
| 🇺🇸 English |      fixed search modal content out of style issue     |
| 🇨🇳 Chinese |     修正了搜索模态内容样式不正确的问题      |
=> fix: fixed search modal content out of style issue

.dumi/theme/builtins/WhoAreUsing/index.tsx
=> chore: use new antv domain

suites/boilerplate/src/index.ts
=> fix(boilerplate): bump dumi's version from rc to release

docs/guide/upgrading.md
fix upgrading guide typo
| 🇺🇸 English |     docs: fix upgrading guide typo      |
| 🇨🇳 Chinese |    docs: 修复升级指南代码拼车错误        |
=> docs: fix upgrading guide typo

src/loaders/markdown/transformer/index.ts, src/loaders/markdown/transformer/rehypeRaw.ts
`<code />` is not supported,  so add warnning for more friendly upgrade
| 🇺🇸 English |      add warning of illegal tag `<code />`      |
| 🇨🇳 Chinese |     增加不合法标签的警告 `<code />`      |
=> chore: add warning of illegal tag `<code />`

docs/guide/page-tab.md, docs/plugin/api.md, src/client/theme-api/types.ts, src/client/theme-default/slots/ContentTabs/index.tsx, src/features/tabs.ts
- [ x ] 新特性提交 / New feature
addContentTab 支持自定义名称
=> feat: addContentTab supports custom names

src/features/routes.ts
没有issue链接
现有的排除规则与文档中的描述不匹配
修改正则表达式，以文档为准
=> fix: wrong regular expression for routes excluding

src/client/theme-default/layouts/DocLayout/index.less
| 🇺🇸 English |  fix scroller style in dark theme          |
| 🇨🇳 Chinese | 修复暗黑主题下滚动条的样式          |
=> fix: change browser scoller style in dark theme

src/client/theme-api/types.ts, src/client/theme-default/slots/PreviewerActions/index.tsx
=> fix: complete the type definitions

docs/guide/page-config.md, suites/boilerplate/templates/site/docs/index.md.tpl
=> perf: title of home

src/client/theme-api/types.ts
=> fix: correct nav type definition

suites/boilerplate/src/index.ts
=> chore: 给默认值

suites/boilerplate/templates/site/docs/guide.md
=> feat: add guide example for site

scripts/sync-from-umi.js
less变量变更，需要更新文档。
| 🇺🇸 English |  doc  replace @primary-color to @c-primary       |
| 🇨🇳 Chinese |  文档更新  将`@primary-color` 变更为 `@c-primary`    |
=> docs: replace theme less doc

docs/guide/page-tab.md, docs/plugin/api.md, src/client/theme-api/types.ts, src/client/theme-default/slots/ContentTabs/index.tsx, src/features/meta.ts, src/features/tabs.ts
修改 addContentTab 参数
close #1425 
=> fix: modify the addContentTab parameter

docs/theme/default.md
| 🇺🇸 English |   update themeConfig.logo config explanation        |
| 🇨🇳 Chinese |    更新 themeConfig.log 配置说明      |
=> docs: update logo config explanation

src/features/exportStatic.ts
无
当启用 `ssr` 和 `exportStatic` 时跳过 demo 独立访问页面的预渲染，以提升站点构建速度，因为 demo 独立页面没有 SEO 需求，相比预渲染对独立打开 demo 时首屏速度的提升，构建速度更为重要
| 🇺🇸 English | Skip pre-render for demo pages when enable ssr with exportStatic |
| 🇨🇳 Chinese | 开启 ssr 和 exportStatic 时跳过 demo 独立页面的预渲染 |
=> perf: skip pre-render for demo pages when enable ssr

src/loaders/markdown/transformer/rehypeImg.ts
当前并不支持在 markdown 里引用指向 data-url 的图片，会报错。
| 🇺🇸 English | support use image with data-url |
| 🇨🇳 Chinese | 支持使用 data-url 插入图片 |
=> feat: support image with data url

suites/theme-mobile/src/builtins/Previewer/index.tsx
无
移除移动端组件研发主题 demoUrl 中无用的 `?`，比如 `/~demos/xxx?` 变成 `/~demos/xxx`，多余的 `?` 可能会导致部分静态站点托管服务的解析错误
| 🇺🇸 English | Remove useless question mark from mobile demo url |
| 🇨🇳 Chinese | 移除移动端组件研发主题 demoUrl 中无用的 `?` |
=> refactor: remove useless question mark from mobile demo url

docs/theme/market.md
| 🇺🇸 English |    docs(dumi-theme): add dumi-theme-antd theme case.    |
| 🇨🇳 Chinese |    docs(dumi-theme): 增加 dumi-theme-antd 主题案例。       |
=> docs(dumi-theme): add dumi-theme-antd theme case

docs/guide/upgrading.md
| 🇺🇸 English | update docs |
| 🇨🇳 Chinese | - |
=> chore: update docs

docs/theme/market.md
=> docs: add antd-style theme

docs/config/demo.md
需要更新一下iframe的参数文档
[源码](https://github.com/umijs/dumi/blob/master/src/client/theme-default/builtins/Previewer/index.tsx#L26-#L37)
=> docs: update iframe docs

src/loaders/markdown/transformer/rehypeDemo.ts
=> fix: writing a line with two code components leads to 100% CPU

src/loaders/markdown/transformer/rehypeDemo.ts
=> fix: #1496  demo 分栏展示异常

docs/theme/default.md, src/client/theme-api/types.ts, src/client/theme-api/useSidebarData.ts, src/client/theme-default/layouts/DocLayout/index.tsx
resolved #1495 
| 🇺🇸 English |     Add a switch to control the visibility of the sidebar menu      |
| 🇨🇳 Chinese |     添加控制侧边栏菜单的显隐功能      |
=> feat: add a switch to control the visibility of the sidebar menu

examples/normal/src/Foo/index.tsx, src/client/theme-default/builtins/API/index.tsx
无
修复 API 表格渲染 DOM 类型失败白屏的问题
| 🇺🇸 English | Fix DOM type render failed bug in API component |
| 🇨🇳 Chinese | 修复 API 表格渲染 DOM 类型失败白屏的问题 |
=> fix: dom type render failed bug in API component

src/client/theme-default/slots/Content/index.less
resolved #1509 
| 🇺🇸 English |      reset table-layout style     |
| 🇨🇳 Chinese |    重置 table-layout 样式       |
=> chore: reset table-layout style

src/client/theme-default/slots/Toc/index.tsx
before：
https://user-images.githubusercontent.com/32004925/222245226-b0692349-1dde-4245-812b-4a0fda6937c0.mp4
after:
https://user-images.githubusercontent.com/32004925/222245872-252cdd21-f631-475e-a495-d8996239795b.mp4
| 🇺🇸 English |    fix page tab click toc error      |
| 🇨🇳 Chinese |    修复页面 Tab 点击 toc 奔溃问题       |
=> fix: fix page tab click toc error

suites/boilerplate/templates/site/.gitignore.tpl
add /dist > .gitignore
| 🇺🇸 English |      site template ignore build product     |
| 🇨🇳 Chinese |    site 模板忽略构建产出       |
=> chore: site template ignore build product

src/client/theme-default/slots/Content/index.less, src/client/theme-default/slots/Content/index.tsx
close #1510
---
| 🇺🇸 English |    Improved no footer theme style       |
| 🇨🇳 Chinese |      改进没有页脚时主题样式     |
=> chore(theme): improved no footer theme style

docs/guide/upgrading.md
网站、文档、Demo 改进 / Website, documentation, demo improvements
=> chore: 📝 针对 monorepo 类型更新 upgrading 文档

src/client/theme-default/builtins/Previewer/index.less, src/client/theme-default/slots/Logo/index.less, src/client/theme-default/slots/Navbar/index.less, src/client/theme-default/slots/Sidebar/index.less
=> style: the color of the navigation selection in light mode.

src/features/exportStatic.ts
| 🇺🇸 English |   Fix that demo page should not be hydrated.        |
| 🇨🇳 Chinese |   修复 demo 页会被注水的问题。        |
=> fix: do not hydrate demo page

src/constants.ts, src/features/derivative.ts
无
默认为 PNPM 项目启用 MFSU，现在 MFSU 已经支持在 PNPM 项目中查找嵌套依赖了
| 🇺🇸 English | Enable MFSU for PNPM project by default |
| 🇨🇳 Chinese | 默认为 PNPM 项目启用 MFSU |
=> refactor: enable mfsu for pnpm project

src/features/derivative.ts
Close #1530 
修复配置 `mfsu.exclude` 配置项时编译失败的问题，原因是用户的 exclude 配置覆盖了默认 exclude 配置
| 🇺🇸 English | Fix compile failed bug if configured mfsu exclude option |
| 🇨🇳 Chinese | 修复配置 `mfsu.exclude` 配置项时编译失败的问题 |
=> fix: compile failed bug if configured mfsu exclude option

src/assetParsers/atom.ts, src/features/parser.ts
无
允许传递 `parseOptions` 配置项给 API 解析器，但目前还未实现任何功能，仅作为预备入口做内部验证
=> refactor: prepare for support api parse options

src/features/exportStatic.ts
since #1548 
修复禁用 `exportStatic` 时构建失败的问题
| 🇺🇸 English | Fix build failed bug when disable `exportStatic` |
| 🇨🇳 Chinese | 修复禁用 `exportStatic` 时构建失败的问题 |
=> fix: build failed bug when disable export static

scripts/sync-from-umi.js, src/features/derivative.ts
Close #1568 
从配置项文档中删除继承自 Umi 且不适用于组件库研发的项，同时在启动时加上前置校验，避免误用
| 🇺🇸 English | -- |
| 🇨🇳 Chinese | -- |
=> docs: remove unsuitable configs for lib development

.dumirc.ts
=> docs: add ga v2 code

src/client/theme-default/builtins/SourceCode/index.tsx
无
当代码块为空白时，默认主题会白屏。
| 🇺🇸 English | Fix the abnormal white screen when the code block is empty |
| 🇨🇳 Chinese | 修复代码块为空时的异常白屏 |
=> fix: crash when code block is empty

docs/guide/initialize.md
=> docs: init

scripts/sync-from-umi.js, src/features/derivative.ts
#1569
默认开启 `esbuildMinifyIIFE`，防止 esbuild 压缩产物中的 helpers 全局变量冲突导致运行时出错
| 🇺🇸 English | Enable esbuildMinifyIIFE by default |
| 🇨🇳 Chinese | 默认开启 esbuildMinifyIIFE |
=> refactor: enable esbuildMinifyIIFE by default

src/features/derivative.ts
Close #1587 
在 pure esm 项目中 MFSU 编译 `@umijs/utils/compiled/strip-ansi` 会出现两层 cjs 劫持（`toESM`），导致 `default` 导出异常出现运行时报错，所以暂时先对 pure esm 项目禁用 MFSU，直到有正确解法
| 🇺🇸 English | Workaround mfsu type error in pure esm project |
| 🇨🇳 Chinese | 绕过在 pure esm 项目中 MFSU 产物异常的问题 |
=> fix: workaround mfsu type error in pure esm project

.github/workflows/ci.yml, Cargo.lock, crates/swc_plugin_react_demo/Cargo.toml, package.json, pnpm-lock.yaml, rust-toolchain, scripts/vercel-install.sh
Close #1594 
修复 SWC 插件产物的 swc_core 与 NPM 的 `@swc/core` 版本不匹配，导致构建失败的问题
| 🇺🇸 English | Fix build exited bug due to swc core version mismatch |
| 🇨🇳 Chinese | 修复 SWC Core 不匹配导致构建退出的问题 |
=> fix: build exited due to swc core version mismatch

suites/boilerplate/templates/theme/.gitignore.tpl, suites/boilerplate/templates/theme/example/package.json.tpl, suites/boilerplate/templates/theme/example/tsconfig.json.tpl, suites/boilerplate/templates/theme/package.json.tpl, suites/boilerplate/templates/theme/tsconfig.json.tpl
#1598 
因生成模板中缺少配置, 导致从 umijs 中代理导出的 api 丢失类型.
=> fix: fix missing export types

src/assetParsers/atom.ts
无
支持通过插件修改 API 解析器的 watch 参数，在某些自定义场景下（比如虚拟化 entry 的小程序组件库）可以通过插件控制 watch 目录，用法：
```ts
// 在 onBeforeCompiler 钩子里调用，因为此时 atomParser 已经实例化到 appData 上且还没调用
api.onBeforeCompiler(() => {
api.appData.atomParser.patchWatchArgs((memo) => {
// 对原有参数做修改，再返回
return memo;
});
});
```
| 🇺🇸 English | Support to patch watch args for api parser |
| 🇨🇳 Chinese | 支持修改 API 解析器的 watch 参数 |
=> feat: support to patch watch args for api parser

src/features/locales.ts
fix #1614, close https://github.com/actions-cool/issues-helper/issues/153
在多语言 Provider 中查找 locales 是进行 base 拼接
| 🇺🇸 English |      fix multi-language switch address error     |
| 🇨🇳 Chinese |    修复多语言切换地址错误问题       |
=> fix: incorrect lang toggle url if configure base

src/features/routes.ts
Close #1612 
修复 2.1.20 内部 alias 使用数组值导致 MFSU 编译失败的问题
| 🇺🇸 English | Fix compile failed bug since internal alias value |
| 🇨🇳 Chinese | 修复内部 alias 使用数组值导致编译失败的问题 |
=> fix: compile failed since internal alias value

docs/theme/default.md
=> docs: modify configuration typos

src/client/theme-api/useSiteSearch/searchWorker.ts
暂无
用超过两个关键词去搜索，只会匹配第一个关键词
| 🇺🇸 English |fix the matching issue when searching with multiple keywords|
| 🇨🇳 Chinese | 解决使用多个关键词进行搜索时的匹配问题 |
=> fix: fix the matching issue when searching with multiple keywords

src/client/theme-default/slots/Toc/index.tsx
https://github.com/umijs/dumi/issues/1636
| 🇺🇸 English |     fixed anchor second click not jump issue      |
| 🇨🇳 Chinese |     修复锚点再次点击不跳转的问题      |
=> fix: toc anchor cannot work if hash already matched

src/client/theme-default/builtins/API/index.tsx
#1638 
声明一个类型 a: string | null
之前API组件会渲染为 string |，修改后可正常展示
| 🇺🇸 English |  Fix API Component not show type null  |
| 🇨🇳 Chinese |  修复API组件不能正常展示null类型的问题 |
=> fix: null type lost in API table

.github/workflows/ci.yml, Cargo.lock, crates/swc_plugin_react_demo/Cargo.toml, package.json, pnpm-lock.yaml
无
dumi 官网 demo 渲染异常，且本地无法复现，排查发现与 SWC 编译 demo 有关系，背后的原因没有再继续排查，这个 PR 先升级 swc core 解决该问题，同时也将包管理器升级到了 pnpm v8
=> chore: upgrade pnpm and swc core

src/client/theme-api/DumiDemoGrid.tsx
https://github.com/ant-design/ant-design/issues/42173
修复 DumiDemoGrid 不响应 items 变化的问题，把 `props.items` 和 route frontmatter 的变化都加入到 effect 依赖里
| 🇺🇸 English | Fix DumiDemoGrid does not response items change |
| 🇨🇳 Chinese | 修复 DumiDemoGrid 不响应 items 变化的问题 |
=> fix: demo grid does not response items change

src/features/theme/index.ts
Close #1655 
修复内置 `nprogress` 的幽灵依赖问题，避免在 PNPM 等隔离幽灵依赖的项目中执行报错
| 🇺🇸 English | Fix phantom dependency problem of nprogress |
| 🇨🇳 Chinese | 修复内置 `nprogress` 的幽灵依赖问题 |
=> fix: phantom dep problem of nprogress

docs/guide/faq.md
- [] 样式优化 / Style optimization
github action gh-pages 的部署脚本更新
=> docs: correct faq of github action yml

src/client/theme-api/types.ts
=> fix: socialLinks theme config should be optional

src/client/theme-api/context.ts, src/client/theme-api/types.ts, src/client/theme-default/layouts/DocLayout/index.tsx, src/features/theme/index.ts
1. keywords  已经在 2009 年被废弃了
2. canonical  设置标准网页格式，避免重复网页
=> feat: generate tag and canonical meta for seo

src/features/sitemap.ts
=> fix: exclude duplicate url in the sitemap

src/client/theme-default/slots/Navbar/index.tsx
=> fix: navbar item key warning in default theme

docs/config/env.md, src/features/theme/index.ts
#1708
支持通过DUMI_THEME环境变量修改主题
| 🇺🇸 English | support DUMI_THEME environment variable to modify theme |
| 🇨🇳 Chinese |  支持DUMI_THEME环境变量修改主题 |
=> feat: support to specific theme path via env

docs/config/env.md, pnpm-lock.yaml, src/features/theme/index.ts, suites/theme-mobile/package.json, suites/theme-mobile/src/slots/PreviewerActions/index.tsx
完善 #1692 
完善 #1709 
包含如下改动：
1. 移动端主题的操作栏二维码地址支持自定义（二次开发场景）
2. 移动端主题的 `extra` 区域支持自定义（二次开发场景）
3. 移动端主题的幽灵依赖修复
4. 环境变量指定主题包路径的逻辑优化，支持 cwd 相对路径
由于对应的两个原始 PR 尚未发布，所以上述改动不进 changelog
| 🇺🇸 English | -- |
| 🇨🇳 Chinese | -- |
=> refactor: improve theme env and mobile actions

src/features/sitemap.ts
=> fix: root path is lost in sitemap

src/features/html2sketch.ts
现在 `html2sketch.js` 是阻塞式加载的. 遇到网络情况不好的时候， 就会阻塞文档的加载. 
使用时机是主动的，所以改为异步加载会好些
=> perf: load html2sketch script with async mode

Cargo.lock, Cargo.toml
无
修复 rust nightly toolchain 升级导致的编译错误，解决方式为更新 lock 文件中的 proc-macro2 依赖为最新版（1.0.66）
=> build: fix rust compile error

scripts/sync-from-umi.js
close: #1776 
| 🇺🇸 English |      --     |
| 🇨🇳 Chinese |      --     |
=> docs: update sync-scripts

scripts/sync-from-umi.js
Close #1837 
修复 Umi 文档同步脚本失效的问题
=> docs: correct sync script for upstream updates

src/client/theme-default/slots/ColorSwitch/index.less
| 🇺🇸 English |      improve of theme switching button hot zone      |
| 🇨🇳 Chinese |    改进主题切换按钮点击热区       |
=> refactor: improve hot zone for theme switch

examples/normal/src/Foo/index.tsx, src/client/theme-default/builtins/API/index.tsx
无
修复 API 表格在渲染不带签名的函数类型时会报错的问题，比如 `onClick: Function`
| 🇺🇸 English | Fix api table error if function has no signature |
| 🇨🇳 Chinese | 修复 API 表格在渲染不带签名的函数类型时会报错的问题 |
=> fix: api table error if function has no signature

src/features/meta.ts, src/templates/meta-runtime.ts.tpl
抽取 runtime 代码到模板
| 🇺🇸 English |       -    |
| 🇨🇳 Chinese |     -      |
=> refactor: move runtime to tpl

src/loaders/markdown/index.ts
=> refactor: load text data from self in markdown loader

examples/normal/src/Foo/demo/work.tsx, package.json, pnpm-lock.yaml, src/templates/ContextWrapper.ts.tpl, src/templates/meta.ts.tpl
ref #1866
移除并警告 demos 废弃
| 🇺🇸 English |       Remove `useSiteData` the `demos` data for load perf enhancement.    |
| 🇨🇳 Chinese |      移除 `useSiteData` 中 `demos` 数据以做加载优化。    |
=> refactor: remove full demos from context

src/templates/ContextWrapper.ts.tpl, src/templates/meta-runtime.ts.tpl, src/templates/meta.ts.tpl
ref #1866
内部调整，移除 `texts` 和 `demos` 引入
| 🇺🇸 English |     -      |
| 🇨🇳 Chinese |     -      |
=> chore: rm texts in fileMetas

src/client/theme-default/slots/Navbar/index.less
#1865 
| 🇺🇸 English |  2-level nav content does not wrap  |
| 🇨🇳 Chinese |  二级导航展示完整内容不换行      |
=> fix: unexpected wrap for 2-level nav item

src/service/forkedDev.ts
#1916 
修复 dev 时不兼容 umi 4.0.82+ 的问题
| 🇺🇸 English | Dev command compatible with umi 4.0.82+ |
| 🇨🇳 Chinese | Dev 命令兼容 umi 4.0.82+ |
=> fix: dev compatible with umi 4.0.82+

examples/normal/.dumirc.ts, src/features/compile/index.ts
close https://github.com/ant-design/ant-design/issues/45201
修复配置 `exportStatic` 时，demo 页没有产出 html 文件的问题
| 🇺🇸 English |      -     |
| 🇨🇳 Chinese |     修复配置 `exportStatic` 时，demo 页没有产出 html 文件的问题      |
=> fix: demo should export html file

suites/boilerplate/src/index.ts
https://github.com/pnpm/pnpm/pull/6987
pnpm 8.7 开始安装策略从 lowerest 办成 highest 了，所以在 create-dumi 里不需要再手动加参数装 latest
| 🇺🇸 English |  Improve create-dumi install for pnpm 8.7+ |
| 🇨🇳 Chinese | 优化使用 pnpm 8.7+ 时 create-dumi 的依赖安装逻辑 |
=> refactor(boilerplate): improve install for pnpm 8.7+

src/client/theme-api/evalCode.ts, src/loaders/markdown/index.ts
| 🇨🇳 Chinese |    修复 demo 的依赖转换正则       |
=> feat: enhance live regexp

src/features/parser.ts
无
修复 API 表格数据不识别 `@ignore` 注解的问题
| 🇺🇸 English | Fix ignored properties still show in api table |
| 🇨🇳 Chinese | 修复标记为 ignore 的属性仍然在 API 表格中展示的问题 |
=> fix: ignored properties still show in api table

src/client/theme-api/usePrefersColor.ts
…stem'
修复在当主题选择为“跟随系统”时，主题展示异常，刷新后正常的问题，具体详见视频：
| 🇺🇸 English | fixed theme display exception when switching theme to 'follow system' |
| 🇨🇳 Chinese | 修复在切换主题为 “跟随系统” 时主题展示异常问题 |
=> fix: preferer color may unexpected when using auto mode

Cargo.lock, crates/swc_plugin_react_demo/Cargo.toml, crates/swc_plugin_react_demo/src/lib.rs, package.json, pnpm-lock.yaml, scripts/sync-from-umi.js
None
Upgrade rust toolchain and swc_core, to fix ci
=> chore: upgrade rust toolchain and swc core

src/assetParsers/block.ts, src/loaders/markdown/transformer/rehypeDemo.ts
v2 版本中，demo 的多语言切换没有实现，v1 中正常
| 🇺🇸 English |      fix: locale not work in demo     |
| 🇨🇳 Chinese |     fix: demo 中多语言设置无效      |
=> fix: demo localized title and description not working bug

src/client/theme-default/slots/ContentFooter/index.less, src/client/theme-default/slots/ContentFooter/index.tsx
在移动端时无需展示最后更新时间的文字描述
Before:
After:
| 🇺🇸 English | Hide the label of last updated time in mobile |
| 🇨🇳 Chinese | 在移动端时无需展示最后更新时间的文字描述 |
=> refactor: improve last updated styles for mobile devices

src/features/compile/index.ts
| 🇺🇸 English |   conditionNames not support ...default        |
| 🇨🇳 Chinese |   conditionNames 不支持 ...      |
=> refactor: correct workaround for condition names

suites/boilerplate/templates/react/package.json.tpl, suites/boilerplate/templates/site/package.json.tpl
#2086
模板代码的 package.json 存在问题。
| 🇺🇸 English | fix: wrong package.json in templates |
| 🇨🇳 Chinese | fix: 修复模板代码 package.json 中的错误 |
=> fix: broken package.json for boilerplates

.github/workflows/release-notify.yml, package.json, pnpm-lock.yaml, scripts/release.ts, suites/boilerplate/package.json, suites/dumi-vue-meta/package.json, suites/father-plugin/package.json, suites/preset-vue/package.json, suites/theme-mobile/package.json
无
此前一直用 `npm version` + `npm publish` 发版，但现在子包变多了，所以添加统一发布脚本便于发版；发布时仍然不强制统一子包版本号，因为相互不耦合
另外加上了 4 号钉群的发布日志推送
=> chore: add release script

src/features/meta.ts, src/features/theme/index.ts, src/templates/ContextWrapper.ts.tpl, src/templates/meta/runtime.ts.tpl
| 🇺🇸 English |      👻 fix: ghost dependency     |
| 🇨🇳 Chinese |     👻  修复幽灵依赖     |
=> fix: rc-util cannot resolve bug in pnpm project

docs/theme/market.md
无
dumi-theme-antd-style 在线地址已经变了 文档需要更新下
| 🇺🇸 English |  update dumi-theme-antd-style theme link address          |
| 🇨🇳 Chinese |   更新  dumi-theme-antd-style 主题跳转链接      |
=> docs: update links for dumi-theme-antd-style

src/features/compile/babelLoaderCustomize.ts
| 🇺🇸 English |   collect wrong dep result for md in mfsu       |
| 🇨🇳 Chinese |  修复 mfsu 收集了错误依赖     |
=> fix: collect wrong dep result for md in mfsu

suites/theme-mobile/src/builtins/Previewer/index.less
书接上回，#2098
`dumi-theme-mobile` 升级到 2.3.0 后问题依旧存在。
| 🇺🇸 English |    fix demo source code overflow       |
| 🇨🇳 Chinese |   修复代码演示源码区域溢出        |
=> fix: demo source code overflow

src/client/theme-api/useRouteMeta.ts
| 🇺🇸 English |  miss metas frontmatter atomId         |
| 🇨🇳 Chinese |   atomId 丢失        |
=> fix: page frontmatter lost from route meta

examples/normal/docs/a/b/c.md, examples/normal/docs/a/b/d.md, src/client/theme-api/useNavData.ts
fix: https://github.com/umijs/dumi/issues/2089
| 🇺🇸 English |    fix: nav title cannot work in singe 2-level directory       |
| 🇨🇳 Chinese |    修复当目录只有一个二级目录时，导航标题使用的是二级导航标题     |
=> fix: nav title cannot work in singe 2-level directory

src/loaders/demo/index.ts
- [] 新特性提交 / New feature
| 🇺🇸 English |   watch-parent  error        |
| 🇨🇳 Chinese |   修复watch-parent 代码拼接问题        |
=> fix: watch parent error

src/features/theme/index.ts
| 🇺🇸 English |     dark mode error      |
| 🇨🇳 Chinese |      暗黑模式 lessloader传参错误    |
=> fix: dark mode error

package.json, pnpm-lock.yaml
file-system-cache 2.4.5 有 break change
| 🇺🇸 English |    lock file-system-cache       |
| 🇨🇳 Chinese |     锁定file-system-cache      |
=> chore(deps:file-system-cache): lock file-system-cache

src/loaders/markdown/index.ts, src/loaders/post-raw/index.ts
demo 内 import 语句中没有处理除`-`以外的特殊字符
| 🇺🇸 English |    handling special characters in specifier       |
| 🇨🇳 Chinese |    处理  specifier 中的特殊字符       |
=> fix:  handling special characters in specifier

src/loaders/markdown/index.ts
livedemo context 只注入了绝对路径依赖, 导致源码变更时运行时 context 缺少依赖
| 🇺🇸 English |    relative deps context inject       |
| 🇨🇳 Chinese |    注入相对路径依赖       |
=> fix: relative deps context inject

src/templates/meta/exports.ts.tpl
重复创建对象, 导致 `g6` 官网搜索性能不佳.
| 🇺🇸 English |   use assignment instead of object spread for better search performance        |
| 🇨🇳 Chinese |   提升搜索性能     |
=> performance: use assignment instead of object spread for better search performance

src/loaders/markdown/index.ts
`windows` 系统下未对 `import` 路径进行处理
=> fix: builtin import path

src/templates/meta/runtime.ts.tpl
#2231 
.md 文件读错字段了, 导致路由没被删除
| 🇺🇸 English |    .md debug mode       |
| 🇨🇳 Chinese |     修复 .md debug 模式在生产的显示问题      |
=> fix: .md debug mode

package.json, pnpm-lock.yaml
react-intl 兼容 react 19 版本
| 🇺🇸 English |    update react intl       |
| 🇨🇳 Chinese |  react-intl 兼容 react 19 版本         |
=> Chore: update react intl

package.json, src/client/theme-api/DumiDemoGrid.tsx
暴露 demo render,  解决 demoGrid 渲染 suspence 阻塞问题
| 🇺🇸 English |   export demo render        |
| 🇨🇳 Chinese |   暴露 demo render        |
=> feat: export demo render

src/client/theme-default/builtins/SourceCode/index.less, src/client/theme-default/builtins/SourceCode/index.tsx
给代码块增加代码language展示, hover 代码块不展示
默认
hover代码块
=> feat: add language badge for SourceCode

crates/swc_plugin_react_demo/src/lib.rs
比如 markdown 中直接默认导出三方库的组件
<pre>
```tsx
export { default } from 'xxx';
```
</pre>
| 🇺🇸 English |     fix(swc-plugin): some edge case      |
| 🇨🇳 Chinese |      修复 swc 插件某些边缘案例     |
=> fix(swc-plugin): some edge case

src/loaders/markdown/index.ts
会导致 #2281 的逻辑改动报错
watch=parent 愿意是给 Mako 用来建立 module graph 依赖关系的，不需要真正编译，该变更仅影响内部实现，理论上不影响提供给用户的功能
=> fix: skip compile watch=parent virtual module
